//! Verifies the committed shader artifacts, and generates the table that names
//! them.
//!
//! **This script never requires a shader compiler.** `cargo build` on a machine
//! with no `slangc` — a contributor's, the macOS and Windows CI legs, the plain
//! `test (linux)` job — does the full check, because the check is SHA-256 over
//! files that are already in the repository. That is the whole point of
//! committing the SPIR-V: `docs/plan/02-vulkan-backend.md`'s risk list says
//! "check in compiled SPIR-V alongside sources until the toolchain story is
//! smooth", and a build that needed the toolchain anyway would have taken the
//! cost without the benefit.
//!
//! What it does, in order:
//!
//! 1. Parses `spirv/manifest.txt`.
//! 2. Fails if any source's SHA-256 differs from the recorded one — "someone
//!    edited the `.slang` and did not regenerate".
//! 3. Fails if any artifact's SHA-256 differs — "the `.spv` is truncated,
//!    corrupt, or was replaced by hand".
//! 4. If a `slangc` matching the pinned version happens to be present,
//!    recompiles and demands the bytes match, which catches the one case
//!    hashing cannot: a manifest regenerated against a *different* source than
//!    the one committed.
//! 5. Writes `$OUT_DIR/shaders.rs`, the static table `src/lib.rs` includes.

use std::path::{Path, PathBuf};
use std::process::Command;

// `#[path]` rather than `include!`: both files open with `//!` module docs, and
// an inner attribute spliced into the middle of a file is a parse error. This
// also keeps them real modules, so they compile identically here and in the
// library — which is the property that makes the library's tests meaningful
// evidence about this script.
//
// `dead_code` because the library uses more of both than a build script needs;
// `cargo clippy --all-targets` lints build scripts too, and `-D warnings`
// would otherwise fail on functions that exist for the other consumer.
#[allow(dead_code)]
#[path = "src/manifest.rs"]
mod manifest;
#[allow(dead_code)]
#[path = "src/sha256.rs"]
mod sha256;

use manifest::{Manifest, ShaderRecord, parse_manifest};
use sha256::sha256_hex;

fn main() {
    let root = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("cargo always sets CARGO_MANIFEST_DIR"),
    );
    let manifest_path = root.join("spirv/manifest.txt");
    println!("cargo::rerun-if-changed=spirv/manifest.txt");
    println!("cargo::rerun-if-changed=tools/compile-shaders.sh");
    println!("cargo::rerun-if-env-changed=CRCBL_SLANGC");

    let text = read(&manifest_path);
    let manifest = match parse_manifest(&text) {
        Ok(manifest) => manifest,
        Err(error) => fail(&format!("spirv/manifest.txt is unreadable: {error}")),
    };

    let slangc = pinned_slangc(&manifest.slangc_version);
    let mut generated = String::new();
    generated.push_str(
        "// @generated by build.rs from spirv/manifest.txt — do not edit.\n\
         // Regenerate the artifacts with tools/compile-shaders.sh.\n\n",
    );
    let mut names = Vec::new();

    for record in &manifest.shaders {
        let source_path = root.join(&record.source);
        let spirv_path = root.join(&record.spirv);
        println!("cargo::rerun-if-changed={}", record.source);
        println!("cargo::rerun-if-changed={}", record.spirv);

        check_hash(&source_path, &record.source_sha256, record, "source");
        check_hash(&spirv_path, &record.spirv_sha256, record, "artifact");

        if let Some(slangc) = slangc.as_deref() {
            recompile_and_compare(slangc, &manifest, record, &root, &spirv_path);
        }

        let ident = record.name.to_uppercase().replace('-', "_");
        let entries: String = record
            .entry_points
            .iter()
            .map(|(name, stage)| {
                let stage = match stage.as_str() {
                    "vertex" => "Vertex",
                    "fragment" => "Fragment",
                    "glcompute" | "compute" => "Compute",
                    other => fail(&format!(
                        "shader `{}` declares entry point `{name}` with execution model \
                         `{other}`, which the seam has no `ShaderStages` bit for",
                        record.name
                    )),
                };
                format!("EntryPoint::new({name:?}, Stage::{stage}), ")
            })
            .collect();

        generated.push_str(&format!(
            "/// The `{name}` shader, compiled from `{source}`.\n\
             pub static {ident}: Shader = Shader::new(\n    \
                 {name:?},\n    \
                 {source:?},\n    \
                 {hash:?},\n    \
                 include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{spirv}\")),\n    \
                 &[{entries}],\n\
             );\n\n",
            name = record.name,
            source = record.source,
            hash = record.source_sha256,
            spirv = record.spirv,
        ));
        names.push(ident);
    }

    generated.push_str(
        "/// Every shader the engine ships, in manifest order.\n\
         ///\n\
         /// The list `crcbl-shaders`' own tests sweep, so a shader that is added\n\
         /// to the manifest but never referenced is still checked for a valid\n\
         /// SPIR-V header and a resolvable entry point.\n\
         pub static ALL: &[&Shader] = &[",
    );
    for name in &names {
        generated.push_str(&format!("&{name}, "));
    }
    generated.push_str("];\n");

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("cargo always sets OUT_DIR"))
        .join("shaders.rs");
    if let Err(error) = std::fs::write(&out, generated) {
        fail(&format!("could not write {}: {error}", out.display()));
    }
}

/// Reads a file, or explains which one was missing.
fn read(path: &Path) -> String {
    match std::fs::read_to_string(path) {
        Ok(text) => text,
        Err(error) => fail(&format!("could not read {}: {error}", path.display())),
    }
}

/// The drift check itself.
fn check_hash(path: &Path, expected: &str, record: &ShaderRecord, what: &str) {
    let Ok(bytes) = std::fs::read(path) else {
        fail(&format!(
            "shader `{}` names {what} `{}`, which does not exist",
            record.name,
            path.display()
        ));
    };
    let actual = sha256_hex(&bytes);
    if actual != expected {
        // Distinguish "someone edited the shader" from "the checkout rewrote
        // the line endings". The second happened for real: `.gitattributes`
        // said `* text=auto`, so a Windows checkout turned every LF into CRLF
        // and the source hash could not match a manifest generated on Linux.
        // `*.slang eol=lf` is the fix; this branch exists so the *next*
        // occurrence names itself instead of looking like an uncommitted edit.
        if sha256_hex(&strip_cr(&bytes)) == expected {
            fail(&format!(
                "shader `{name}`: {what} `{path}` differs from the manifest only in line \
                 endings — this checkout converted LF to CRLF.\n\nThe file is marked \
                 `eol=lf` in .gitattributes; re-clone, or run `git add --renormalize .`, \
                 rather than regenerating the manifest.",
                name = record.name,
                path = path.display(),
            ));
        }
        fail(&format!(
            "shader `{name}`: the committed {what} has changed without the manifest \
             being regenerated.\n  {path}\n  expected sha256 {expected}\n  actual   sha256 \
             {actual}\n\nRun crates/crcbl-shaders/tools/compile-shaders.sh and commit the \
             result. A rendering change that shifts output must also re-bless its golden \
             image (docs/plan/12-testing.md).",
            name = record.name,
            path = path.display(),
        ));
    }
}

/// `bytes` with every `\r\n` collapsed to `\n`.
///
/// Only used to explain a hash mismatch — never to accept one. Normalising
/// before hashing would paper over the line-ending problem instead of naming
/// it, and would make `build.rs` and `compile-shaders.sh` compute different
/// numbers for the same file.
fn strip_cr(bytes: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(bytes.len());
    let mut index = 0;
    while index < bytes.len() {
        if bytes[index] == b'\r' && bytes.get(index + 1) == Some(&b'\n') {
            index += 1;
            continue;
        }
        out.push(bytes[index]);
        index += 1;
    }
    out
}

/// A `slangc` on `PATH` (or at `CRCBL_SLANGC`) whose version is the pinned one.
///
/// Absent is the normal case and is silent: warning on every build of every
/// contributor who has no shader compiler would be noise about a state the
/// design deliberately supports. A *mismatched* version is worth one line,
/// because it is the state in which the byte check silently stops running.
fn pinned_slangc(pinned: &str) -> Option<String> {
    let slangc = std::env::var("CRCBL_SLANGC").unwrap_or_else(|_| "slangc".to_string());
    let output = Command::new(&slangc).arg("-v").output().ok()?;
    // Slang prints its version on stderr.
    let mut text = String::from_utf8_lossy(&output.stderr).into_owned();
    text.push_str(&String::from_utf8_lossy(&output.stdout));
    let version = text.lines().map(str::trim).rfind(|line| !line.is_empty())?;
    if version == pinned {
        Some(slangc)
    } else {
        println!(
            "cargo::warning=slangc {version} is not the pinned {pinned}; the committed SPIR-V \
             is hash-checked but not byte-checked in this build"
        );
        None
    }
}

/// Recompiles one shader and demands byte-for-byte equality.
fn recompile_and_compare(
    slangc: &str,
    manifest: &Manifest,
    record: &ShaderRecord,
    root: &Path,
    committed: &Path,
) {
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("cargo always sets OUT_DIR"))
        .join(format!("{}.check.spv", record.name));
    let status = Command::new(slangc)
        .arg(root.join(&record.source))
        .args(["-target", "spirv"])
        .args(["-profile", &manifest.target])
        .arg("-emit-spirv-directly")
        .arg("-o")
        .arg(&out)
        .status();
    match status {
        Ok(status) if status.success() => {}
        // A compiler that is present but cannot compile the source is a real
        // problem, but it is not *this* build's problem: the committed artifact
        // is already hash-verified and is what will be used.
        _ => {
            println!(
                "cargo::warning=slangc could not recompile {}; the committed artifact is \
                 hash-checked but not byte-checked",
                record.source
            );
            return;
        }
    }
    let (Ok(fresh), Ok(old)) = (std::fs::read(&out), std::fs::read(committed)) else {
        return;
    };
    if fresh != old {
        fail(&format!(
            "shader `{name}`: recompiling {source} with the pinned slangc produces different \
             bytes than the committed {spirv}.\n\nThis is the case a hash cannot catch — the \
             manifest agrees with both files, but they do not agree with each other. Run \
             crates/crcbl-shaders/tools/compile-shaders.sh and commit the result.",
            name = record.name,
            source = record.source,
            spirv = record.spirv,
        ));
    }
}

/// Stops the build with a message a reader can act on.
///
/// `panic!` rather than `cargo::error=`: a build script panic prints the whole
/// message and fails the build on every toolchain this workspace supports,
/// whereas `cargo::error` is newer than the pinned rustc's guarantees.
fn fail(message: &str) -> ! {
    panic!("crcbl-shaders: {message}");
}
