//! Verifies the committed shader artifacts, and generates the table that names
//! them.
//!
//! **This script never requires a shader compiler.** `cargo build` on a machine
//! with no `slangc` — a contributor's, the macOS and Windows CI legs, the plain
//! `test (linux)` job — does the full check, because the check is SHA-256 over
//! files that are already in the repository. That is the whole point of
//! committing the SPIR-V: `docs/plan/02-vulkan-backend.md`'s risk list says
//! "check in compiled SPIR-V alongside sources until the toolchain story is
//! smooth", and a build that needed the toolchain anyway would have taken the
//! cost without the benefit.
//!
//! What it does, in order:
//!
//! 1. Parses `spirv/manifest.txt` — which is also where each shader's declared
//!    target list is held to the artifact columns beside it, so "a target this
//!    shader says it must support was never built" fails here rather than on
//!    the machine that tried to use it.
//! 2. Fails if any source's SHA-256 differs from the recorded one — "someone
//!    edited the `.slang` and did not regenerate".
//! 3. Fails if any artifact's SHA-256 differs — "the `.spv`, `.wgsl`, `.metal`
//!    or `.dxil` is truncated, corrupt, or was replaced by hand".
//! 4. If a `slangc` matching the pinned version happens to be present,
//!    recompiles **every** target and demands the bytes match, which catches
//!    the one case hashing cannot: a manifest regenerated against a *different*
//!    source than the one committed. DXIL needs a pinned `dxc` at `CRCBL_DXC`
//!    as well, because it is compiled in two steps — see
//!    `tools/compile-shaders.sh` for why Slang's own `-target dxil` is not used
//!    and why that variable never falls back to `PATH`.
//! 5. Writes `$OUT_DIR/shaders.rs`, the static table `src/lib.rs` includes.

use std::path::{Path, PathBuf};
use std::process::Command;

// `#[path]` rather than `include!`: both files open with `//!` module docs, and
// an inner attribute spliced into the middle of a file is a parse error. This
// also keeps them real modules, so they compile identically here and in the
// library — which is the property that makes the library's tests meaningful
// evidence about this script.
//
// `dead_code` because the library uses more of both than a build script needs;
// `cargo clippy --all-targets` lints build scripts too, and `-D warnings`
// would otherwise fail on functions that exist for the other consumer.
#[allow(dead_code)]
#[path = "src/manifest.rs"]
mod manifest;
#[allow(dead_code)]
#[path = "src/sha256.rs"]
mod sha256;

use manifest::{DxilArtifact, Manifest, ShaderRecord, parse_manifest};
use sha256::sha256_hex;

fn main() {
    let root = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("cargo always sets CARGO_MANIFEST_DIR"),
    );
    let manifest_path = root.join("spirv/manifest.txt");
    println!("cargo::rerun-if-changed=spirv/manifest.txt");
    println!("cargo::rerun-if-changed=tools/compile-shaders.sh");
    println!("cargo::rerun-if-env-changed=CRCBL_SLANGC");
    println!("cargo::rerun-if-env-changed=CRCBL_DXC");

    let text = read(&manifest_path);
    let manifest = match parse_manifest(&text) {
        Ok(manifest) => manifest,
        Err(error) => fail(&format!("spirv/manifest.txt is unreadable: {error}")),
    };

    let slangc = pinned_slangc(&manifest.slangc_version);
    let dxc = pinned_dxc(&manifest.dxc_version);
    let mut generated = String::new();
    generated.push_str(
        "// @generated by build.rs from spirv/manifest.txt — do not edit.\n\
         // Regenerate the artifacts with tools/compile-shaders.sh.\n\n",
    );
    let mut names = Vec::new();

    for record in &manifest.shaders {
        let source_path = root.join(&record.source);
        let spirv_path = root.join(&record.spirv);
        println!("cargo::rerun-if-changed={}", record.source);
        println!("cargo::rerun-if-changed={}", record.spirv);

        // The two optional columns, handled identically. Absent is a legal
        // state for both — a manifest predating the target — and an absent one
        // is skipped rather than compared against an empty hash.
        let optional = [
            (Target::Wgsl, &record.wgsl, &record.wgsl_sha256),
            (Target::Msl, &record.msl, &record.msl_sha256),
        ];
        for (target, artifact, hash) in optional {
            if artifact.is_empty() {
                continue;
            }
            println!("cargo::rerun-if-changed={artifact}");
            check_hash(&root.join(artifact), hash, record, target.artifact_name());
        }

        // One container per entry point, so this is a loop where the columns
        // above are a pair of scalars.
        for artifact in &record.dxil {
            println!("cargo::rerun-if-changed={}", artifact.path);
            check_hash(
                &root.join(&artifact.path),
                &artifact.sha256,
                record,
                &format!("DXIL artifact for `{}`", artifact.entry_point),
            );
        }

        check_hash(&source_path, &record.source_sha256, record, "source");
        check_hash(&spirv_path, &record.spirv_sha256, record, "SPIR-V artifact");

        if let (Some(slangc), Some(dxc)) = (slangc.as_deref(), dxc.as_deref()) {
            for artifact in &record.dxil {
                recompile_dxil(slangc, dxc, &manifest, record, &root, artifact);
            }
        }
        if let Some(slangc) = slangc.as_deref() {
            recompile(
                slangc,
                &manifest,
                record,
                &root,
                Target::SpirV,
                &record.spirv,
                &spirv_path,
            );
            for (target, artifact, _) in optional {
                if artifact.is_empty() {
                    continue;
                }
                recompile(
                    slangc,
                    &manifest,
                    record,
                    &root,
                    target,
                    artifact,
                    &root.join(artifact),
                );
            }
        }

        let ident = record.name.to_uppercase().replace('-', "_");
        let entries: String = record
            .entry_points
            .iter()
            .map(|(name, stage)| {
                let stage = match stage.as_str() {
                    "vertex" => "Vertex",
                    "fragment" => "Fragment",
                    "glcompute" | "compute" => "Compute",
                    other => fail(&format!(
                        "shader `{}` declares entry point `{name}` with execution model \
                         `{other}`, which the seam has no `ShaderStages` bit for",
                        record.name
                    )),
                };
                // The DXIL container hangs off the entry point rather than off
                // the shader, because `dxc` compiles one entry point per
                // container. A shader with no DXIL column at all gets `b""`,
                // which `EntryPoint::dxil` reports as absent.
                let dxil = record
                    .dxil
                    .iter()
                    .find(|artifact| artifact.entry_point == *name)
                    .map_or_else(
                        || "b\"\"".to_string(),
                        |artifact| optional_include(&artifact.path),
                    );
                format!("EntryPoint::new({name:?}, Stage::{stage}, {dxil}), ")
            })
            .collect();

        let wgsl_include = optional_include(&record.wgsl);
        let msl_include = optional_include(&record.msl);

        generated.push_str(&format!(
            "/// The `{name}` shader, compiled from `{source}`.\n\
             pub static {ident}: Shader = Shader::new(\n    \
                 {name:?},\n    \
                 {source:?},\n    \
                 {hash:?},\n    \
                 include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/\", {spirv:?})),\n    \
                 {wgsl_include},\n    \
                 {msl_include},\n    \
                 &[{entries}],\n\
             );\n\n",
            name = record.name,
            source = record.source,
            hash = record.source_sha256,
            spirv = record.spirv,
        ));
        names.push(ident);
    }

    generated.push_str(
        "/// Every shader the engine ships, in manifest order.\n\
         ///\n\
         /// The list `crcbl-shaders`' own tests sweep, so a shader that is added\n\
         /// to the manifest but never referenced is still checked for a valid\n\
         /// SPIR-V header and a resolvable entry point.\n\
         pub static ALL: &[&Shader] = &[",
    );
    for name in &names {
        generated.push_str(&format!("&{name}, "));
    }
    generated.push_str("];\n");

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("cargo always sets OUT_DIR"))
        .join("shaders.rs");
    if let Err(error) = std::fs::write(&out, generated) {
        fail(&format!("could not write {}: {error}", out.display()));
    }
}

/// The generated initialiser for an optional artifact column: an
/// `include_bytes!` of the committed file, or `b""` for a shader that has none.
///
/// `{:?}` rather than `{}` for the path, as for the `name`/`source` fields: a
/// manifest path containing a quote or a backslash would otherwise close the
/// generated string literal and inject arbitrary code into
/// `$OUT_DIR/shaders.rs`.
fn optional_include(artifact: &str) -> String {
    if artifact.is_empty() {
        return "b\"\"".to_string();
    }
    format!("include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/\", {artifact:?}))")
}

/// Reads a file, or explains which one was missing.
fn read(path: &Path) -> String {
    match std::fs::read_to_string(path) {
        Ok(text) => text,
        Err(error) => fail(&format!("could not read {}: {error}", path.display())),
    }
}

/// The drift check itself.
fn check_hash(path: &Path, expected: &str, record: &ShaderRecord, what: &str) {
    let Ok(bytes) = std::fs::read(path) else {
        fail(&format!(
            "shader `{}` names {what} `{}`, which does not exist",
            record.name,
            path.display()
        ));
    };
    let actual = sha256_hex(&bytes);
    if actual != expected {
        // Distinguish "someone edited the shader" from "the checkout rewrote
        // the line endings". The second happened for real: `.gitattributes`
        // said `* text=auto`, so a Windows checkout turned every LF into CRLF
        // and the source hash could not match a manifest generated on Linux.
        // `*.slang eol=lf` is the fix; this branch exists so the *next*
        // occurrence names itself instead of looking like an uncommitted edit.
        if sha256_hex(&strip_cr(&bytes)) == expected {
            fail(&format!(
                "shader `{name}`: {what} `{path}` differs from the manifest only in line \
                 endings — this checkout converted LF to CRLF.\n\nThe file is marked \
                 `eol=lf` in .gitattributes; re-clone, or run `git add --renormalize .`, \
                 rather than regenerating the manifest.",
                name = record.name,
                path = path.display(),
            ));
        }
        fail(&format!(
            "shader `{name}`: the committed {what} has changed without the manifest \
             being regenerated.\n  {path}\n  expected sha256 {expected}\n  actual   sha256 \
             {actual}\n\nRun crates/crcbl-shaders/tools/compile-shaders.sh and commit the \
             result. A rendering change that shifts output must also re-bless its golden \
             image (docs/plan/12-testing.md).",
            name = record.name,
            path = path.display(),
        ));
    }
}

/// `bytes` with every `\r\n` collapsed to `\n`.
///
/// Only used to explain a hash mismatch — never to accept one. Normalising
/// before hashing would paper over the line-ending problem instead of naming
/// it, and would make `build.rs` and `compile-shaders.sh` compute different
/// numbers for the same file.
fn strip_cr(bytes: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(bytes.len());
    let mut index = 0;
    while index < bytes.len() {
        if bytes[index] == b'\r' && bytes.get(index + 1) == Some(&b'\n') {
            index += 1;
            continue;
        }
        out.push(bytes[index]);
        index += 1;
    }
    out
}

/// A `slangc` on `PATH` (or at `CRCBL_SLANGC`) whose version is the pinned one.
///
/// Absent is the normal case and is silent: warning on every build of every
/// contributor who has no shader compiler would be noise about a state the
/// design deliberately supports. A *mismatched* version is worth one line,
/// because it is the state in which the byte check silently stops running.
fn pinned_slangc(pinned: &str) -> Option<String> {
    let slangc = std::env::var("CRCBL_SLANGC").unwrap_or_else(|_| "slangc".to_string());
    let output = Command::new(&slangc).arg("-v").output().ok()?;
    // Slang prints its version on stderr.
    let mut text = String::from_utf8_lossy(&output.stderr).into_owned();
    text.push_str(&String::from_utf8_lossy(&output.stdout));

    // Every non-empty line, not just the last one. Taking `rfind` meant any
    // trailing output — a deprecation notice, a shell wrapper's own banner —
    // silently downgraded the byte-for-byte check to hash-only with nothing but
    // a `cargo::warning` to say so.
    let lines: Vec<&str> = text
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .collect();
    if lines.iter().any(|line| names_version(line, pinned)) {
        return Some(slangc);
    }
    let reported = lines.last().copied().unwrap_or("<no output>");
    println!(
        "cargo::warning=slangc reported {reported:?}, which does not name the pinned {pinned}; \
         the committed SPIR-V is hash-checked but not byte-checked in this build"
    );
    None
}

/// A `dxc` at `CRCBL_DXC` reporting the pinned version, or `None`.
///
/// **There is deliberately no `PATH` fallback**, unlike [`pinned_slangc`]:
/// distributions ship Shader Model 6.10 preview builds of `dxc` that abort on a
/// trivial shader, and a fallback would find one. `tools/compile-shaders.sh`
/// makes the same call and says more about it.
///
/// Absent is silent for the same reason it is there: no shader compiler is the
/// normal case and the design supports it. `pinned` empty — a manifest with no
/// DXIL column at all — is absent too, because there is nothing to recompile.
fn pinned_dxc(pinned: &str) -> Option<String> {
    if pinned.is_empty() {
        return None;
    }
    let dxc = std::env::var("CRCBL_DXC").ok()?;
    let output = Command::new(&dxc).arg("--version").output().ok()?;
    let mut text = String::from_utf8_lossy(&output.stdout).into_owned();
    text.push_str(&String::from_utf8_lossy(&output.stderr));

    // `dxc` prints `libdxcompiler.so: 1.9(…)`, naming the library it *loaded*
    // rather than itself, and the prefix differs by platform — so the pin is on
    // what follows the colon.
    let reported = text
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .any(|line| {
            line.split_once(": ")
                .is_some_and(|(_, rest)| rest == pinned)
        });
    if reported {
        return Some(dxc);
    }
    println!(
        "cargo::warning=CRCBL_DXC does not report the pinned {pinned}; the committed DXIL is \
         hash-checked but not byte-checked in this build"
    );
    None
}

/// Whether one line of `slangc -v` output names `pinned`.
///
/// Slang prints a bare version on some builds and `slangc <version>` on others,
/// so both shapes count — but a line that merely *contains* the digits does
/// not, or a path like `/opt/slang-2026.14/bin` would pass.
fn names_version(line: &str, pinned: &str) -> bool {
    line == pinned || line.split_whitespace().any(|word| word == pinned)
}

/// One of Slang's output targets, and the artifact column it fills.
///
/// Every column gets the same treatment for the same reason: a manifest hash
/// agrees with a file that nobody checked came from the committed source. The
/// WGSL is what the wgpu backend actually compiles and the MSL is what the
/// Metal backend hands to `newLibraryWithSource:`, so leaving either hash-only
/// would have made a *rendering* backend the least-checked artifact.
#[derive(Clone, Copy)]
enum Target {
    SpirV,
    Wgsl,
    Msl,
}

impl Target {
    /// What `-target` calls it, which is also the extension the check file
    /// gets.
    const fn flag(self) -> &'static str {
        match self {
            Self::SpirV => "spirv",
            Self::Wgsl => "wgsl",
            Self::Msl => "metal",
        }
    }

    /// How a hash-mismatch message names this column.
    const fn artifact_name(self) -> &'static str {
        match self {
            Self::SpirV => "SPIR-V artifact",
            Self::Wgsl => "WGSL artifact",
            Self::Msl => "MSL artifact",
        }
    }

    /// The macro `tools/compile-shaders.sh` defines while compiling this
    /// target, and which this script must define too.
    ///
    /// Slang defines no target macro of its own — probing found only
    /// `__SLANG_COMPILER__`, which is true everywhere — so these are how a
    /// shader writes a `#if` that differs per target at all. They are named
    /// after the language coming *out*: [`Target::Msl`] is emitted by
    /// `-target metal`, and the HLSL step [`recompile_dxil`] runs defines
    /// [`HLSL_DEFINE`].
    ///
    /// **This list and the script's must stay identical.** A define present on
    /// one side and not the other changes the preprocessor state the artifact
    /// was produced under, so every byte comparison below fails for a reason
    /// that is not drift.
    const fn define(self) -> &'static str {
        match self {
            Self::SpirV => "CRCBL_TARGET_SPIRV=1",
            Self::Wgsl => "CRCBL_TARGET_WGSL=1",
            Self::Msl => "CRCBL_TARGET_MSL=1",
        }
    }
}

/// The define for the HLSL leg, which has no [`Target`] because DXIL is reached
/// in two steps rather than by one `-target`. See [`Target::define`].
const HLSL_DEFINE: &str = "CRCBL_TARGET_HLSL=1";

/// Recompiles one shader to one target and demands byte-for-byte equality.
fn recompile(
    slangc: &str,
    manifest: &Manifest,
    record: &ShaderRecord,
    root: &Path,
    target: Target,
    artifact: &str,
    committed: &Path,
) {
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("cargo always sets OUT_DIR"))
        .join(format!("{}.check.{}", record.name, target.flag()));
    let mut command = Command::new(slangc);
    command
        // From the crate root, naming the source the way the manifest does —
        // which is the way `tools/compile-shaders.sh` names it. Slang copies the
        // path it was *given* into the `#line` directives of its Metal output,
        // so passing `root.join(...)` here produced an artifact that differed
        // from the committed one by an absolute path on every machine that had
        // the pinned compiler. That failed the build rather than the check,
        // and only for developers who had installed `slangc` — which is to say,
        // only for the people editing shaders.
        .current_dir(root)
        .arg(&record.source)
        .args(["-target", target.flag()])
        .args(["-profile", &manifest.target])
        .args(["-D", target.define()]);
    if matches!(target, Target::SpirV) {
        // Both flags must match `tools/compile-shaders.sh` exactly, or this
        // recompile disagrees with the committed artifact for a reason that is
        // not drift. See that script for what each one is for.
        command.arg("-emit-spirv-directly");
        command.arg("-fvk-use-entrypoint-name");
    }
    let status = command.arg("-o").arg(&out).status();
    match status {
        Ok(status) if status.success() => {}
        // A compiler that is present but cannot compile the source is a real
        // problem, but it is not *this* build's problem: the committed artifact
        // is already hash-verified and is what will be used.
        _ => {
            println!(
                "cargo::warning=slangc could not recompile {} to {}; the committed artifact is \
                 hash-checked but not byte-checked",
                record.source,
                target.flag()
            );
            return;
        }
    }
    let (Ok(fresh), Ok(old)) = (std::fs::read(&out), std::fs::read(committed)) else {
        return;
    };
    if fresh != old {
        fail(&format!(
            "shader `{name}`: recompiling {source} with the pinned slangc produces different \
             bytes than the committed {artifact}.\n\nThis is the case a hash cannot catch — the \
             manifest agrees with both files, but they do not agree with each other. Run \
             crates/crcbl-shaders/tools/compile-shaders.sh and commit the result.",
            name = record.name,
            source = record.source,
        ));
    }
}

/// Recompiles one entry point to DXIL and demands byte-for-byte equality.
///
/// Two steps rather than one, matching `tools/compile-shaders.sh` exactly:
/// `slangc -target hlsl` for one entry point, then `dxc` at the manifest's
/// shader model. Slang's own `-target dxil` shells out to whichever `dxc` it
/// finds, which is the ambient compiler this pin exists to exclude.
fn recompile_dxil(
    slangc: &str,
    dxc: &str,
    manifest: &Manifest,
    record: &ShaderRecord,
    root: &Path,
    artifact: &DxilArtifact,
) {
    let Some((_, model)) = record
        .entry_points
        .iter()
        .find(|(name, _)| *name == artifact.entry_point)
    else {
        // `manifest::finish` rejects this, so reaching it means the parser and
        // this script disagree — which is worth failing over rather than
        // skipping a check.
        fail(&format!(
            "shader `{}`: DXIL artifact for `{}` names no declared entry point",
            record.name, artifact.entry_point
        ));
    };
    let Some(profile) = dxil_profile(model, &manifest.dxil_model) else {
        fail(&format!(
            "shader `{}`: entry point `{}` has execution model `{model}`, which no DXIL profile \
             covers",
            record.name, artifact.entry_point
        ));
    };

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("cargo always sets OUT_DIR"));
    let hlsl = out_dir.join(format!(
        "{}.{}.check.hlsl",
        record.name, artifact.entry_point
    ));
    let dxil = out_dir.join(format!(
        "{}.{}.check.dxil",
        record.name, artifact.entry_point
    ));
    // `current_dir` and the manifest's own spelling of the source path, for the
    // reason `recompile` gives: Slang copies the path it was given into the
    // `#line` directives of its HLSL, and an absolute one would differ per
    // machine.
    let hlsl_status = Command::new(slangc)
        .current_dir(root)
        .arg(&record.source)
        .args(["-target", "hlsl"])
        .args(["-entry", &artifact.entry_point])
        .args(["-stage", slang_stage(model)])
        .args(["-D", HLSL_DEFINE])
        .arg("-o")
        .arg(&hlsl)
        .status();
    let dxil_status = match hlsl_status {
        Ok(status) if status.success() => Command::new(dxc)
            .args(["-T", &profile])
            .args(["-E", &artifact.entry_point])
            .arg("-Fo")
            .arg(&dxil)
            .arg(&hlsl)
            .status(),
        _ => {
            println!(
                "cargo::warning=slangc could not recompile {} to HLSL; the committed DXIL is \
                 hash-checked but not byte-checked",
                record.source
            );
            return;
        }
    };
    match dxil_status {
        Ok(status) if status.success() => {}
        _ => {
            println!(
                "cargo::warning=dxc could not recompile {}:{} to DXIL; the committed artifact is \
                 hash-checked but not byte-checked",
                record.source, artifact.entry_point
            );
            return;
        }
    }
    let (Ok(fresh), Ok(old)) = (
        std::fs::read(&dxil),
        std::fs::read(root.join(&artifact.path)),
    ) else {
        return;
    };
    if fresh != old {
        fail(&format!(
            "shader `{name}`: recompiling {source}:{entry} with the pinned slangc and dxc \
             produces different bytes than the committed {path}.\n\nThis is the case a hash \
             cannot catch — the manifest agrees with both files, but they do not agree with each \
             other. Run crates/crcbl-shaders/tools/compile-shaders.sh and commit the result.",
            name = record.name,
            source = record.source,
            entry = artifact.entry_point,
            path = artifact.path,
        ));
    }
}

/// The `dxc -T` profile for a SPIR-V execution model at a shader model, or
/// `None` for a model no graphics or compute profile covers.
fn dxil_profile(model: &str, shader_model: &str) -> Option<String> {
    let prefix = match model {
        "vertex" => "vs",
        "fragment" => "ps",
        "glcompute" | "compute" => "cs",
        _ => return None,
    };
    Some(format!("{prefix}_{shader_model}"))
}

/// What `slangc -stage` calls a SPIR-V execution model.
const fn slang_stage(model: &str) -> &str {
    match model.as_bytes() {
        b"glcompute" => "compute",
        _ => model,
    }
}

/// Stops the build with a message a reader can act on.
///
/// `panic!` rather than `cargo::error=`: a build script panic prints the whole
/// message and fails the build on every toolchain this workspace supports,
/// whereas `cargo::error` is newer than the pinned rustc's guarantees.
fn fail(message: &str) -> ! {
    panic!("crcbl-shaders: {message}");
}
