//! The brick grid, as a `.scn/` scene directory.
//!
//! `assets/scenes/board.scn/` is breakout's board: a header, an environment and
//! one chunk file holding a [`Brick`] per row of the grid. It is read through
//! [`crcbl::scene::scn`], which is the engine's own scene format — the
//! directory of chunk files `docs/notes/tooling.md` records under _What the
//! deleted 06-assets-scenes plan left behind_.
//!
//! ```text
//! assets/scenes/board.scn/
//!   scene.ron        format version, name, the system manifest
//!   env.ron          the camera the field is viewed from, and its surround
//!   sys/bricks.ron   one Brick(position, half_extents) per brick
//! ```
//!
//! # Two sources, one loader
//!
//! The committed files are `include_str!`ed and read back through a
//! [`MemorySource`], for the reason `apps/lantern/src/args.rs`'s
//! `BUILT_IN_STACK_RON` gives about its camera: a browser has no filesystem, and
//! a binary that could fail to find its own board is one whose golden depends on
//! the working directory it was run from. `--scene <DIR>` is the run-time door,
//! and it is a door onto a *different* directory, opened with a
//! [`DirSource`] — the same [`Scene::load`] call either way, because that is
//! what an [`AssetSource`] is for.
//!
//! # The file's entities are the layout, not the live bricks
//!
//! [`Board::load`] spawns the chunk's rows into a [`World`] of its own and reads
//! them straight back out. That world is the parse and nothing more: a brick the
//! ball breaks is despawned, and `game::restart` puts the whole grid back, so
//! the entities the game plays with cannot be the ones the file named — they are
//! spawned, destroyed and spawned again while the layout stays put. Keeping the
//! scene's world separate also keeps the game's own spawn order exactly what it
//! was before the board came out of a file, which is what
//! `tests/golden/board.png` is a picture of.
//!
//! # What keeps the committed file honest
//!
//! `game::brick_position` is still the layout's generator:
//! `the_committed_board_is_what_the_writer_writes` builds the grid from it,
//! writes it with [`Scene::save`], and asserts the result is byte-for-byte the
//! three committed files. So the files are generated by the writer once and
//! maintained that way — a hand-typed `7.8000000000000005` is written back as
//! `7.8`, and the test would be about the typist rather than about the board.

use std::path::Path;

use crcbl::assets::{AssetSource, DirSource, MemorySource};
use crcbl::ecs::{ComponentHash, System, World};
use crcbl::math::DVec3;
use crcbl::reflect::Reflect;
use crcbl::registry::{Placement, Registry};
use crcbl::scene::scn::{Scene, ScnError};
use crcbl::serde::{Deserialize, Serialize};

/// The one system a breakout board is made of, and so the manifest entry, the
/// chunk file's stem and the name the codec is registered under.
const BRICKS: &str = "bricks";

/// The directory `--scene` defaults to, relative to nothing: the committed
/// board is compiled in, and this is the name its keys are spelled under.
///
/// Public because [`built_in_source`] is, and a source whose keys nobody can
/// spell is a source nobody can read.
pub const BOARD: &str = "board.scn";

/// `assets/scenes/board.scn/scene.ron`, as it is committed.
const BOARD_SCENE_RON: &str = include_str!("../assets/scenes/board.scn/scene.ron");
/// `assets/scenes/board.scn/env.ron`, as it is committed.
const BOARD_ENV_RON: &str = include_str!("../assets/scenes/board.scn/env.ron");
/// `assets/scenes/board.scn/sys/bricks.ron`, as it is committed.
const BOARD_BRICKS_RON: &str = include_str!("../assets/scenes/board.scn/sys/bricks.ron");

/// One brick of the grid: where it stands and how big it is.
///
/// Both in world units and both `f64`, because that is what the physics world
/// they reach is spelled in — `crcbl::phys::Transform` and
/// `ColliderComponent::Box` take [`DVec3`], and a board written as `f32` would
/// round on the way through the file and move the picture.
///
/// **The first component an editor edits.**
/// `docs/plan/08-editor.md`'s smallest slice is a tool that loads this board,
/// picks a brick and nudges it, so [`Reflect`] is derived here rather than on a
/// fixture: the property panel's rows are these two fields, and a range on the
/// half extents is what keeps a drag from inverting a collider. The two derives
/// answer different questions and both are needed — `Serialize` is how the row
/// reaches `sys/bricks.ron`, `Reflect` is how it reaches a widget.
#[derive(Clone, Copy, Debug, PartialEq, Reflect, Serialize, Deserialize)]
#[reflect(crate = "crcbl::reflect")]
#[serde(crate = "crcbl::serde")]
pub struct Brick {
    /// The brick's centre.
    #[reflect(name = "Position")]
    pub position: [f64; 3],
    /// Half its extent on each axis, which is the box collider's own shape.
    ///
    /// The range is the playfield's own: a half extent is never negative, and
    /// nothing on this board is wider than the span `crate::game`'s
    /// `WORLD_LEFT` and `WORLD_RIGHT` bound, so a drag past that has left the
    /// picture. Advisory — it bounds the widget, not the write.
    #[reflect(name = "Half extents", min = 0.0, max = 28.0, step = 0.01)]
    pub half_extents: [f64; 3],
}

impl Brick {
    /// The centre, as the physics world wants it.
    #[must_use]
    pub fn position(&self) -> DVec3 {
        DVec3::from_array(self.position)
    }

    /// The half extents, as the collider wants them.
    #[must_use]
    pub fn half_extents(&self) -> DVec3 {
        DVec3::from_array(self.half_extents)
    }
}

impl ComponentHash for Brick {
    fn hash_component(&self, hasher: &mut dyn std::hash::Hasher) {
        for value in self.position.iter().chain(&self.half_extents) {
            hasher.write(&value.to_bits().to_le_bytes());
        }
    }
}

/// A brick's own box, which is what its collider already is.
///
/// The two fields spell a centre and half extents directly, so this is the
/// identity — and it is still worth having, because it is what lets a tool ask
/// *where* a row is without knowing that a brick's position is called
/// `position`. See [`crcbl::registry::Placement`].
impl Placement for Brick {
    fn placement(&self) -> Option<(DVec3, DVec3)> {
        Some((self.position(), self.half_extents()))
    }
}

/// This game's scene vocabulary: one component, under the name its chunk file is
/// spelled with.
///
/// **The one place `bricks` is joined to [`Brick`].** [`Board::load`] uses it and
/// so does any tool that opens this game's board, so the vocabulary the game
/// ships and the vocabulary an editor sees are the same list rather than two that
/// agree today — `docs/plan/08-editor.md`'s component registry.
pub fn register_components(registry: &mut Registry) {
    registry.register::<Brick>(BRICKS);
}

/// A board's brick layout, in the order its chunk file spells it.
///
/// Not `Eq`: the positions are floats. [`PartialEq`] is what
/// `crate::args::Options` needs and all a test comparing two parses of one file
/// wants.
#[derive(Clone, Debug, PartialEq)]
pub struct Board {
    bricks: Vec<Brick>,
}

impl Board {
    /// The committed `assets/scenes/board.scn/`, parsed.
    ///
    /// # Panics
    ///
    /// If the committed directory is not a scene, naming the key, the line and
    /// the column. It is compiled into this binary, so that is a tree in which
    /// `the_committed_board_is_what_the_writer_writes` is also red — the panic
    /// is what keeps a run from starting on a board nobody could read.
    #[must_use]
    pub fn built_in() -> Self {
        Self::load(&built_in_source(), Path::new(BOARD))
            .unwrap_or_else(|error| panic!("apps/breakout/assets/scenes/{BOARD}: {error}"))
    }

    /// The board `dir` holds, read through `source`.
    ///
    /// # Errors
    ///
    /// [`ScnError`], which names the key it is about: a file that is not there,
    /// text that is not this format, a header this build does not read, or a
    /// manifest naming a system that is not `bricks`.
    pub fn load(source: &dyn AssetSource, dir: &Path) -> Result<Self, ScnError> {
        let mut registry = Registry::new();
        register_components(&mut registry);
        let mut world = World::new();
        registry.register_systems(&mut world);
        let (_scene, ids) = Scene::load(source, dir, &registry.codecs(), &mut world)?;

        // Sorted by the file's own id rather than taken in storage order, so
        // the grid is spawned in the order the chunk spells it however the ECS
        // happened to lay the rows out.
        let system = world
            .system_mut::<System<Brick>>()
            .expect("the system this function registered is in the world it registered it in");
        let mut rows: Vec<_> = system
            .iter_entities()
            .map(|(entity, brick)| (ids.id(entity), *brick))
            .collect();
        rows.sort_by_key(|(id, _)| *id);
        Ok(Self {
            bricks: rows.into_iter().map(|(_, brick)| brick).collect(),
        })
    }

    /// The board the directory at `path` holds, or the message to refuse the
    /// run with.
    ///
    /// Both failures read the same way — the path, then what went wrong with
    /// it — because to a person fixing it "no such file" and "line 3, column 5"
    /// are the same kind of answer about the same argument. The shape
    /// `apps/lantern/src/args.rs`'s `read_stack` has.
    ///
    /// # Errors
    ///
    /// The refusal message, ready to print.
    pub fn read_dir(path: &str) -> Result<Self, String> {
        // Rooted at the scene directory itself and read with an empty prefix:
        // `DirSource` refuses an absolute key and a `..`, so the root is how a
        // caller says where the scene is.
        let source = DirSource::at(std::path::PathBuf::from(path));
        Self::load(&source, Path::new("")).map_err(|error| format!("{path}: {error}"))
    }

    /// The bricks, in file order.
    #[must_use]
    pub fn bricks(&self) -> &[Brick] {
        &self.bricks
    }
}

/// The committed scene directory, as a source with no filesystem under it,
/// keyed under [`BOARD`].
///
/// Public so that a **tool** can open this game's board without one: `.scn/` is
/// the engine's own scene format, `apps/editor` opens this board as its default
/// document, and a tool that had to find `apps/breakout/assets/` on disk would
/// be one whose behaviour depended on the directory it was started from. The
/// game reads it through [`Board::built_in`], which is this source and the
/// loader over it.
#[must_use]
pub fn built_in_source() -> MemorySource {
    let mut source = MemorySource::new();
    for (key, text) in [
        ("scene.ron", BOARD_SCENE_RON),
        ("env.ron", BOARD_ENV_RON),
        ("sys/bricks.ron", BOARD_BRICKS_RON),
    ] {
        // `format!` and not `Path::join`: an asset key is `/`-separated on
        // every host, and a key joined on Windows would not be one anywhere
        // else.
        source
            .insert(
                Path::new(&format!("{BOARD}/{key}")),
                text.as_bytes().to_vec(),
            )
            .expect("a nested scene key is a legal asset key");
    }
    source
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    use crcbl::reflect::{Kind, Range, Value, get_path, set_path};
    use crcbl::scene::scn::{Env, EnvCamera, IdMap};

    use crate::game::{BRICK_COUNT, BRICK_HEIGHT, BRICK_WIDTH, brick_position};

    /// The environment the committed `env.ron` holds.
    ///
    /// The camera is where `crate::audio` puts the mixer's listener — back
    /// [`crate::audio::LISTENER_STANDOFF`] from the play plane, aimed at the
    /// middle of the field — because there is one camera in this game and the
    /// listener is at it. The ambient is [`crate::art::SURROUND`], the linear
    /// clear the court sits in, which is the only light breakout has: its
    /// sprites are unlit, so nothing else could fill this in truthfully.
    ///
    /// Both are read from the constants rather than retyped, so a change to
    /// either is a red test here rather than a file that quietly disagrees with
    /// the game.
    ///
    /// Neither reaches the renderer yet — the orthographic camera's extent is
    /// derived from the surface's aspect in `crate::gpu::camera_half_width`,
    /// and the clear is `art::SURROUND` directly. `env.ron` is a file the
    /// format requires and this test is what keeps its numbers from drifting
    /// away from the two constants they were taken from.
    fn env() -> Env {
        Env {
            camera: EnvCamera {
                position: [0.0, 0.0, -crate::audio::LISTENER_STANDOFF],
                look_at: [0.0, 0.0, 0.0],
            },
            ambient: [
                crate::art::SURROUND[0],
                crate::art::SURROUND[1],
                crate::art::SURROUND[2],
            ],
        }
    }

    /// The board `game::brick_position` describes, in a world of its own, ready
    /// to be written out.
    ///
    /// The Z half-extent is the one number here with no constant behind it: the
    /// field is flat, so a brick's depth only has to be enough for a sphere
    /// swept at `z = 0` to hit it, and it is the same `0.5` the grid was always
    /// spawned with.
    fn generated() -> (Scene, IdMap, World) {
        let mut world = World::new();
        world.register_system(Box::new(System::<Brick>::new(BRICKS)));
        let mut ids = IdMap::new();
        let mut rows = Vec::with_capacity(BRICK_COUNT);
        for index in 0..BRICK_COUNT {
            let entity = world.spawn();
            ids.assign(entity);
            rows.push((
                entity,
                Brick {
                    position: brick_position(index).to_array(),
                    half_extents: [BRICK_WIDTH / 2.0, BRICK_HEIGHT / 2.0, 0.5],
                },
            ));
        }
        let system = world
            .system_mut::<System<Brick>>()
            .expect("just registered");
        for (entity, brick) in rows {
            system.attach(entity, brick);
        }
        let scene = Scene::new("board", vec![BRICKS.to_string()], env());
        (scene, ids, world)
    }

    /// Asserts a committed file is what the writer wrote, and says *where* it
    /// stopped agreeing when it is not.
    ///
    /// Line by line rather than as two strings: a chunk file is one row per
    /// brick, and an `assert_eq!` over the pair prints both in full for one
    /// changed coordinate.
    ///
    /// Byte for byte, on every platform: `.gitattributes` pins `*.ron` to LF,
    /// so a Windows checkout hands `include_str!` the bytes the repository
    /// holds and nothing here has to fold a CRLF the transport might have
    /// added.
    fn assert_committed(key: &str, written: &str, committed: &str) {
        if written == committed {
            return;
        }
        match written
            .lines()
            .zip(committed.lines())
            .position(|(written, committed)| written != committed)
        {
            Some(line) => panic!(
                "{key} line {}: the writer writes `{}`, the file has `{}`",
                line + 1,
                written.lines().nth(line).expect("the line just compared"),
                committed.lines().nth(line).expect("the line just compared"),
            ),
            None => panic!(
                "{key}: the writer writes {} lines, the file has {}",
                written.lines().count(),
                committed.lines().count(),
            ),
        }
    }

    /// **The committed board is exactly what the writer writes** from
    /// `game::brick_position`, which is what lets the layout live in a
    /// file without a second copy of it in code.
    ///
    /// Generated once by [`Scene::save`] and maintained that way: ron prints a
    /// float through Rust's shortest-round-trip `Display`, which round-trips a
    /// *parsed* value and not a typed one, so a hand-edited coordinate is a
    /// failure here rather than a board that quietly moved.
    #[test]
    fn the_committed_board_is_what_the_writer_writes() {
        let (scene, ids, mut world) = generated();
        // This game's own registration rather than a second list, so the writer
        // test is about the vocabulary the game ships.
        let mut registry = Registry::new();
        register_components(&mut registry);
        let files = scene
            .save(&mut world, &ids, &registry.codecs())
            .expect("a generated board is writable");

        assert_committed("scene.ron", &files["scene.ron"], BOARD_SCENE_RON);
        assert_committed("env.ron", &files["env.ron"], BOARD_ENV_RON);
        assert_committed("sys/bricks.ron", &files["sys/bricks.ron"], BOARD_BRICKS_RON);
        assert_eq!(
            files.keys().collect::<Vec<_>>(),
            ["env.ron", "scene.ron", "sys/bricks.ron"],
            "the manifest's files and nothing else"
        );
        for (key, text) in &files {
            assert!(!text.contains('\r'), "the newline is pinned in {key}");
        }
    }

    /// The other half of the same claim: what the committed files *parse* to is
    /// the grid the game used to build in code. A writer that agreed with
    /// itself while dropping a field would pass the byte comparison above.
    #[test]
    fn the_committed_board_parses_to_the_grid_the_code_generates() {
        let board = Board::built_in();
        assert_eq!(board.bricks().len(), BRICK_COUNT);
        for (index, brick) in board.bricks().iter().enumerate() {
            assert_eq!(
                brick.position(),
                brick_position(index),
                "brick {index} moved"
            );
            assert_eq!(
                brick.half_extents(),
                DVec3::new(BRICK_WIDTH / 2.0, BRICK_HEIGHT / 2.0, 0.5),
                "brick {index} changed size"
            );
        }
    }

    /// A directory with no `scene.ron` is refused by the key that is missing,
    /// and the key is spelled the way `--scene` points at it — the scene
    /// directory *is* the root, so the header is `scene.ron` and not
    /// `board.scn/scene.ron`. A loader looking under the built-in name would
    /// report a file the caller never named.
    #[test]
    fn a_directory_with_no_header_is_refused_by_the_missing_key() {
        let dir = std::env::temp_dir().join(format!("breakout-empty-{}.scn", std::process::id()));
        std::fs::create_dir_all(&dir).expect("the temp dir is writable");
        let message = Board::read_dir(dir.to_str().expect("utf-8"))
            .expect_err("a directory with no scene.ron is not a board");
        assert!(message.contains("scene.ron"), "{message}");
        assert!(message.contains("path not found"), "{message}");
        assert!(
            !message.contains(BOARD),
            "the key must be the caller's, not the built-in board's: {message}"
        );
    }

    /// A directory whose header is not RON is refused by line and column, so a
    /// person fixing it is told where to look.
    #[test]
    fn a_header_that_is_not_ron_is_refused_by_line_and_column() {
        let dir = std::env::temp_dir().join(format!("breakout-bad-{}.scn", std::process::id()));
        std::fs::create_dir_all(&dir).expect("the temp dir is writable");
        std::fs::write(
            dir.join("scene.ron"),
            "Scene(\n    format: 0,\n    nome: \"board\",\n)",
        )
        .expect("the temp dir is writable");
        let message = Board::read_dir(dir.to_str().expect("utf-8"))
            .expect_err("a header that is not a scene is not a board");
        assert!(message.contains("scene.ron"), "{message}");
        assert!(message.contains("line"), "{message}");
        assert!(message.contains("column"), "{message}");
    }

    // -- reflection ----------------------------------------------------------

    #[test]
    fn a_brick_describes_the_two_rows_a_property_panel_draws() {
        let brick = Brick {
            position: [1.0, 2.0, 3.0],
            half_extents: [BRICK_WIDTH / 2.0, BRICK_HEIGHT / 2.0, 0.5],
        };

        assert_eq!(crcbl::reflect::Reflect::type_name(&brick), "Brick");
        assert_eq!(crcbl::reflect::Reflect::kind(&brick), Kind::Struct);

        let rows = crcbl::reflect::Reflect::fields(&brick);
        assert_eq!(
            rows.iter().map(|row| row.label).collect::<Vec<_>>(),
            ["Position", "Half extents"]
        );
        assert_eq!(rows[0].range, None, "a centre may be anywhere on the board");
        assert_eq!(
            rows[1].range,
            Some(Range {
                min: 0.0,
                max: 28.0
            }),
            "a half extent is never negative and never wider than the playfield"
        );
    }

    #[test]
    fn an_edit_to_a_brick_reads_back_and_undoes() {
        let mut brick = Brick {
            position: [1.0, 2.0, 3.0],
            half_extents: [1.2, 0.4, 0.5],
        };
        let before = brick;

        let old = get_path(&brick, "position.0").expect("the row is an f64");
        assert_eq!(old, Value::Float(1.0));
        set_path(&mut brick, "position.0", &Value::Float(-6.5)).expect("an f64 takes a float");
        assert_eq!(brick.position(), DVec3::new(-6.5, 2.0, 3.0));

        set_path(&mut brick, "position.0", &old).expect("the recorded value");
        assert_eq!(brick, before);
    }
}
