//! The `.scn/` directory's three writer properties, over a two-system scene.
//!
//! `docs/plan/06-assets-scenes.md`'s "Deterministic writer" section names them:
//! load → save is byte-identical, editing one entity moves only its own lines,
//! and — the one a single-chunk scene cannot express — moving an entity between
//! systems rewrites those two chunk files and nothing else.
//!
//! The fixture below is **generated by the writer** and maintained that way, the
//! discipline `crcbl_inventory::catalog`'s `CANONICAL` encodes. It matters more
//! here than there: ron's float output is Rust's own shortest-round-trip
//! `Display`, which round-trips a *parsed* value exactly, so a hand-typed
//! `7.8000000000000005` would be written back as `7.8` and fail a test that is
//! about the writer rather than about the typist.

use std::collections::BTreeMap;
use std::collections::hash_map::DefaultHasher;
use std::hash::Hasher;
use std::path::Path;

use crcbl_assets::{AssetSource, DirSource, MemorySource};
use crcbl_ecs::{ComponentHash, System, World};
use crcbl_scene::scn::{IdMap, Scene, SceneEntityId, SystemChunk, chunk_of};
use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// A two-system world
// ---------------------------------------------------------------------------

/// The first system's component: a placed thing with a colour.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
struct Prop {
    position: [f32; 3],
    tint: [f32; 3],
}

/// The second system's component, a different shape on purpose — a chunk file
/// that reads as either type would make the third property untestable.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
struct Light {
    position: [f32; 3],
    intensity: f32,
}

impl ComponentHash for Prop {
    fn hash_component(&self, hasher: &mut dyn Hasher) {
        hash_floats(hasher, &self.position);
        hash_floats(hasher, &self.tint);
    }
}

impl ComponentHash for Light {
    fn hash_component(&self, hasher: &mut dyn Hasher) {
        hash_floats(hasher, &self.position);
        hash_floats(hasher, &[self.intensity]);
    }
}

/// Hashes floats by their bits, which is what [`ComponentHash`]'s contract asks
/// for: the value, padding-free, and not the object's address.
fn hash_floats(hasher: &mut dyn Hasher, values: &[f32]) {
    for value in values {
        hasher.write(&value.to_bits().to_le_bytes());
    }
}

const SCENE_RON: &str = r#"Scene(
    format: 0,
    name: "yard",
    systems: [
        "props",
        "lights",
    ],
)"#;

const ENV_RON: &str = r#"Env(
    camera: Camera(
        position: (0.0, 3.0, 24.0),
        look_at: (0.0, 3.0, 0.0),
    ),
    ambient: (0.05, 0.05, 0.08),
)"#;

const PROPS_RON: &str = r#"Chunk(
    system: "props",
    entities: [
        (0, Prop(
            position: (-13.0, 7.0, 0.0),
            tint: (0.8, 0.2, 0.2),
        )),
        (1, Prop(
            position: (-10.4, 7.0, 0.0),
            tint: (0.2, 0.8, 0.3),
        )),
        (2, Prop(
            position: (-7.8, 7.0, 0.0),
            tint: (0.1, 0.35, 0.9),
        )),
    ],
)"#;

const LIGHTS_RON: &str = r#"Chunk(
    system: "lights",
    entities: [
        (3, Light(
            position: (0.0, 12.0, 4.0),
            intensity: 120.0,
        )),
        (4, Light(
            position: (6.5, 9.25, -2.0),
            intensity: 47.5,
        )),
    ],
)"#;

/// The scene directory as an in-memory source, which is the browser's shape and
/// needs no filesystem to be a test.
fn fixture() -> MemorySource {
    let mut source = MemorySource::new();
    for (key, text) in files() {
        source
            .insert(Path::new(&format!("yard.scn/{key}")), text.into_bytes())
            .expect("a scene key is a legal asset key");
    }
    source
}

fn files() -> BTreeMap<String, String> {
    [
        ("scene.ron", SCENE_RON),
        ("env.ron", ENV_RON),
        ("sys/props.ron", PROPS_RON),
        ("sys/lights.ron", LIGHTS_RON),
    ]
    .into_iter()
    .map(|(key, text)| (key.to_string(), text.to_string()))
    .collect()
}

fn codecs() -> Vec<Box<dyn SystemChunk>> {
    vec![chunk_of::<Prop>("props"), chunk_of::<Light>("lights")]
}

/// A world with both systems registered and nothing in them.
fn empty_world() -> World {
    let mut world = World::new();
    world.register_system(Box::new(System::<Prop>::new("props")));
    world.register_system(Box::new(System::<Light>::new("lights")));
    world
}

fn load(source: &dyn AssetSource, dir: &str) -> (Scene, IdMap, World) {
    let mut world = empty_world();
    let (scene, ids) = Scene::load(source, Path::new(dir), &codecs(), &mut world)
        .expect("the fixture scene loads");
    (scene, ids, world)
}

/// The determinism hash `docs/notes/process.md` asks the scene roundtrip to
/// end at: every system's component state, independent of registration and
/// attach order.
fn state_hash(world: &World) -> u64 {
    let mut hasher = DefaultHasher::new();
    world.hash_state(&mut hasher);
    hasher.finish()
}

// ---------------------------------------------------------------------------
// Property 1 — save is byte-stable
// ---------------------------------------------------------------------------

/// **A scene written out reads back the same, byte for byte, through a real
/// directory.**
///
/// The round trip is asserted on the *text* first, because a writer that
/// reordered fields, printed `2` for a float or emitted `\r\n` would still
/// compare equal after a second parse, and what a data file in git needs is that
/// the bytes do not move. The second half is the parsed value and the world's
/// determinism hash, so a writer that agreed with itself while dropping a field
/// cannot pass on the text alone.
#[test]
fn a_scene_written_out_reads_back_the_same() {
    let (scene, ids, mut world) = load(&fixture(), "yard.scn");
    let written = scene
        .save(&mut world, &ids, &codecs())
        .expect("the loaded scene writes");
    assert_eq!(written, files(), "the writer is not the file");

    // Through a directory, which is what a native save actually is: the keys
    // have to be usable as paths and as asset keys both.
    let root = tempfile::tempdir().expect("a temp dir");
    for (key, text) in &written {
        let path = root.path().join(key);
        std::fs::create_dir_all(path.parent().expect("keys are relative")).expect("mkdir");
        std::fs::write(&path, text).expect("write");
        assert!(!text.contains('\r'), "the newline is pinned in {key}");
    }

    let source = DirSource::at(root.path().to_path_buf());
    for (key, text) in &written {
        assert_eq!(
            source.read(Path::new(key)).expect("what was just written"),
            text.as_bytes(),
            "{key} is not what was written"
        );
    }

    let (reloaded, reloaded_ids, reloaded_world) = load(&source, ".");
    assert_eq!(reloaded, scene, "the parsed header and env moved");
    assert_eq!(reloaded_ids.len(), ids.len());
    assert_eq!(
        state_hash(&reloaded_world),
        state_hash(&world),
        "save → load is not the identity on component state"
    );

    // And the second save writes the same bytes as the first.
    let mut reloaded_world = reloaded_world;
    assert_eq!(
        reloaded
            .save(&mut reloaded_world, &reloaded_ids, &codecs())
            .expect("the reloaded scene writes"),
        written,
    );
}

// ---------------------------------------------------------------------------
// Property 2 — one edit, one diff
// ---------------------------------------------------------------------------

/// **Editing one entity moves only that entity's own lines.**
///
/// This is the classic Unity/Godot diff-noise bug the plan bans by name: an id
/// regenerated on save, or an iteration order that is a function of attach
/// history, moves every row and turns a one-field edit into a whole-file diff.
#[test]
fn editing_one_entity_touches_only_its_lines() {
    let (scene, ids, mut world) = load(&fixture(), "yard.scn");

    let middle = ids.entity(SceneEntityId(1)).expect("the fixture names it");
    world
        .system_mut::<System<Prop>>()
        .expect("the world holds it")
        .get_mut(middle)
        .expect("entity 1 is a prop")
        .position = [-10.4, 7.5, 0.0];

    let written = scene
        .save(&mut world, &ids, &codecs())
        .expect("the edited scene writes");

    assert_eq!(
        written["scene.ron"], SCENE_RON,
        "an entity edit is not a header edit"
    );
    assert_eq!(written["env.ron"], ENV_RON);
    assert_eq!(
        written["sys/lights.ron"], LIGHTS_RON,
        "an edit in one system is not a diff in another"
    );

    let moved = changed_lines(PROPS_RON, &written["sys/props.ron"]);
    assert_eq!(
        moved,
        vec![(8, "            position: (-10.4, 7.0, 0.0),".to_string())],
        "the diff is not the one field that changed"
    );
}

/// The 0-based line numbers of `before` whose text `after` does not repeat, with
/// the old text beside them.
///
/// Line-for-line rather than a real diff because the property under test is that
/// the files stay the same *shape*: a writer that inserted or dropped a line
/// would fail the length assertion first, and one that moved a row would report
/// every line it touched.
fn changed_lines(before: &str, after: &str) -> Vec<(usize, String)> {
    let after: Vec<&str> = after.lines().collect();
    let before: Vec<&str> = before.lines().collect();
    assert_eq!(before.len(), after.len(), "the file changed length");
    before
        .iter()
        .zip(&after)
        .enumerate()
        .filter(|(_, (old, new))| old != new)
        .map(|(index, (old, _))| (index, (*old).to_string()))
        .collect()
}

// ---------------------------------------------------------------------------
// Property 3 — a move is two chunk files
// ---------------------------------------------------------------------------

/// **Moving an entity from one system to another rewrites exactly those two
/// chunk files.**
///
/// The property a one-chunk scene cannot express, and the whole argument for a
/// directory rather than a document: the header and the environment are
/// untouched, so two people editing different systems have nothing to merge.
#[test]
fn moving_one_entity_changes_one_chunk_file() {
    let (scene, ids, mut world) = load(&fixture(), "yard.scn");

    let last = ids.entity(SceneEntityId(2)).expect("the fixture names it");
    let prop = world
        .system_mut::<System<Prop>>()
        .expect("the world holds it")
        .detach(last)
        .expect("entity 2 is a prop");
    world
        .system_mut::<System<Light>>()
        .expect("the world holds it")
        .attach(
            last,
            Light {
                position: prop.position,
                intensity: 12.5,
            },
        );

    let written = scene
        .save(&mut world, &ids, &codecs())
        .expect("the moved scene writes");
    let before = files();
    let changed: Vec<&String> = written
        .keys()
        .filter(|key| written[*key] != before[*key])
        .collect();
    assert_eq!(
        changed,
        vec!["sys/lights.ron", "sys/props.ron"],
        "a move is exactly two chunk files"
    );

    // The row left one file and arrived in the other under the id it had.
    assert!(!written["sys/props.ron"].contains("(2, Prop("));
    assert!(written["sys/lights.ron"].contains("(2, Light("));
    assert!(
        written["sys/lights.ron"].find("(2, Light(") < written["sys/lights.ron"].find("(3, Light("),
        "the arrival is filed by id, not appended:\n{}",
        written["sys/lights.ron"],
    );

    // And it survives a reload: the scene the file describes is the one in the
    // world it was written from.
    let mut source = MemorySource::new();
    for (key, text) in &written {
        source
            .insert(Path::new(key), text.clone().into_bytes())
            .expect("a legal asset key");
    }
    let (_, _, reloaded) = load(&source, ".");
    assert_eq!(state_hash(&reloaded), state_hash(&world));
}
