//! Bakes `assets/*.crpix` — the menu's shared art — into the PNG + sidecar pair
//! [`crcbl_sprite::load`] reads, and generates the table `src/menu.rs` includes.
//!
//! ```text
//! assets/menu.crpix ──parse──▶ CrpixArt ──bake──▶ $OUT_DIR/menu.png
//!                                              └─▶ $OUT_DIR/menu.json
//!                                          │
//!                                          └──▶ $OUT_DIR/menu_art.rs  (include_bytes!)
//! ```
//!
//! # Why a renderer crate has art in it
//!
//! Because the menu is the one picture **every sample draws and no sample
//! owns**. `apps/*` cannot depend on each other, so the alternative is the same
//! window frame authored three times — three times the drawing, and three games
//! whose menus look like three different engines. `src/menu.rs` carries the
//! argument in full, including the option that was rejected (a shared `assets/`
//! directory both build scripts reach into).
//!
//! # This is `apps/*/build.rs` for the third time, and that is a finding
//!
//! `apps/breakout/build.rs` and `apps/flappy/build.rs` are already the same
//! script with a different `ASSETS` array, and `docs/backlog.md` has carried the
//! duplication since they were written. This is the third copy and it does not
//! close it — the fix is a real `crcbl_sprite::bake::bake_dir` entry point, and
//! it is a change to `crcbl-sprite` rather than to any of the three callers. The
//! backlog entry now names three.

use std::path::{Path, PathBuf};

/// The tick rate the frame holds are baked against.
///
/// Nothing in the menu animates — the three button frames are states, not a
/// clip — so no hold here is anything but the default of one tick. It is
/// declared because a `.crpix` counts holds in ticks and an Aseprite sidecar
/// counts milliseconds, and the two conversions must use the same rate or every
/// hold silently changes. `src/menu.rs`'s `ART_TICK_HZ` is the other half.
const ART_TICK_HZ: u32 = 60;

/// The sheets, by file stem. Each is `assets/<stem>.crpix`.
///
/// One, and the array stays because the next shared sheet should not have to
/// reintroduce the loop.
const ASSETS: [&str; 1] = ["menu"];

fn main() {
    let root = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("cargo always sets CARGO_MANIFEST_DIR"),
    );
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("cargo always sets OUT_DIR"));

    let mut table = String::from(
        "// @generated by build.rs from crates/crcbl-render/assets/*.crpix — do not edit.\n\n",
    );

    for stem in ASSETS {
        let relative = format!("assets/{stem}.crpix");
        // Without this the baked PNG in OUT_DIR is a cached artifact of a source
        // cargo has never been told about, and a redrawn frame shows up on the
        // next `cargo clean` and not before.
        println!("cargo::rerun-if-changed={relative}");

        let source = root.join(&relative);
        let text = std::fs::read_to_string(&source)
            .unwrap_or_else(|error| fail(&format!("{relative}: {error}")));
        let art = crcbl_sprite::crpix::parse(&text)
            .unwrap_or_else(|error| fail(&format!("{relative}:{error}")));

        let image = format!("{stem}.png");
        let baked = crcbl_sprite::bake::bake(&art, &image, ART_TICK_HZ)
            .unwrap_or_else(|error| fail(&format!("{relative}: {error}")));

        let png = out.join(&image);
        write(&png, &baked.png);
        let upper = stem.to_uppercase();
        table.push_str(&format!(
            "pub(crate) static {upper}_PNG: &[u8] = include_bytes!({:?});\n",
            png.display().to_string()
        ));

        match &baked.json {
            Some(json) => {
                let sidecar = out.join(format!("{stem}.json"));
                write(&sidecar, json.as_bytes());
                table.push_str(&format!(
                    "pub(crate) static {upper}_JSON: Option<&str> = Some(include_str!({:?}));\n",
                    sidecar.display().to_string()
                ));
            }
            // A single still frame is fully described by its image; the loader
            // takes `None` and reads one frame covering the whole picture.
            None => table.push_str(&format!(
                "pub(crate) static {upper}_JSON: Option<&str> = None;\n"
            )),
        }
    }

    write(&out.join("menu_art.rs"), table.as_bytes());
}

fn write(path: &Path, bytes: &[u8]) {
    std::fs::write(path, bytes)
        .unwrap_or_else(|error| fail(&format!("writing {}: {error}", path.display())));
}

/// Fails the build with a message cargo shows, rather than a panic backtrace.
fn fail(message: &str) -> ! {
    println!("cargo::error={message}");
    std::process::exit(1);
}
