//! The scene format's own tests: the writer's canonical text, every refusal
//! by name, and the id map.

use std::hash::Hasher;

use crcbl_assets::MemorySource;
use crcbl_ecs::System;

use super::*;

/// One system's component, in the shape a real one has: a couple of floats
/// and a name.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
struct Mark {
    position: [f32; 3],
    label: String,
}

impl ComponentHash for Mark {
    fn hash_component(&self, hasher: &mut dyn Hasher) {
        for value in self.position {
            hasher.write(&value.to_bits().to_le_bytes());
        }
        hasher.write(self.label.as_bytes());
    }
}

const HEADER: &str =
    "Scene(\n    format: 0,\n    name: \"one\",\n    systems: [\n        \"marks\",\n    ],\n)";
const ENV: &str = "Env(\n    camera: Camera(\n        position: (0.0, 2.0, 8.0),\n        look_at: (0.0, 0.0, 0.0),\n    ),\n    ambient: (0.05, 0.05, 0.08),\n)";
const MARKS: &str = "Chunk(\n    system: \"marks\",\n    entities: [\n        (0, Mark(\n            position: (1.0, 0.0, -1.0),\n            label: \"first\",\n        )),\n    ],\n)";

fn source(header: &str, env: &str, marks: &str) -> MemorySource {
    let mut source = MemorySource::new();
    for (key, text) in [
        ("one.scn/scene.ron", header),
        ("one.scn/env.ron", env),
        ("one.scn/sys/marks.ron", marks),
    ] {
        source
            .insert(Path::new(key), text.as_bytes().to_vec())
            .expect("a nested scene key is a legal asset key");
    }
    source
}

fn world_with_marks() -> World {
    let mut world = World::new();
    world.register_system(Box::new(System::<Mark>::new("marks")));
    world
}

fn codecs() -> Vec<Box<dyn SystemChunk>> {
    vec![chunk_of::<Mark>("marks")]
}

fn load(header: &str, env: &str, marks: &str) -> Result<(Scene, IdMap, World), ScnError> {
    let source = source(header, env, marks);
    let mut world = world_with_marks();
    let (scene, ids) = Scene::load(&source, Path::new("one.scn"), &codecs(), &mut world)?;
    Ok((scene, ids, world))
}

/// **The canonical trio is exactly what the writer writes**, which is the
/// discipline that keeps a committed scene honest: the fixtures above are
/// generated by this writer, so a change to the configuration moves them
/// and has to be blessed rather than absorbed.
#[test]
fn the_canonical_scene_is_what_the_writer_writes() {
    let (scene, ids, mut world) = load(HEADER, ENV, MARKS).expect("the canonical scene loads");
    let files = scene
        .save(&mut world, &ids, &codecs())
        .expect("a scene that loaded can be written");

    assert_eq!(files["scene.ron"], HEADER);
    assert_eq!(files["env.ron"], ENV);
    assert_eq!(files["sys/marks.ron"], MARKS);
    assert_eq!(
        files.keys().collect::<Vec<_>>(),
        ["env.ron", "scene.ron", "sys/marks.ron"],
        "the manifest's files and nothing else"
    );

    for (key, text) in &files {
        assert!(!text.contains('\r'), "the newline is pinned in {key}");
    }

    assert_eq!(scene.name(), "one");
    assert_eq!(scene.systems(), ["marks"]);
    assert_eq!(scene.env().camera.position, [0.0, 2.0, 8.0]);
    assert_eq!(scene.env().ambient, [0.05, 0.05, 0.08]);
    assert_eq!(ids.len(), 1);
    assert!(!ids.is_empty());
}

/// **A version this build does not know is refused, not read as the current
/// one.** [`Scene::FORMAT`]'s doc says why that matters more than a
/// migration would.
#[test]
fn a_scene_of_another_format_is_refused_by_number() {
    let error = load(&HEADER.replace("format: 0", "format: 1"), ENV, MARKS)
        .expect_err("format 1 is not this build's");
    assert!(
        matches!(&error, ScnError::Format { key, found, expected }
            if key == "one.scn/scene.ron" && *found == 1 && *expected == Scene::FORMAT),
        "{error}"
    );
    assert!(error.to_string().contains("one.scn/scene.ron"), "{error}");
}

/// **A field nothing reads is refused where it is written.** Every file type
/// sets `deny_unknown_fields`, so a typo is a position rather than a value
/// silently defaulted.
#[test]
fn an_unknown_field_is_refused_with_the_position_ron_gives() {
    let error = load(HEADER, &ENV.replace("ambient", "ambent"), MARKS)
        .expect_err("an unknown field is not an env");
    let ScnError::Parse {
        key,
        line,
        column,
        message,
    } = &error
    else {
        panic!("{error}");
    };
    assert_eq!(key, "one.scn/env.ron");
    assert!(*line > 1, "the position is ron's, not zero");
    assert!(*column >= 1);
    assert!(message.contains("ambent"), "ron names the field: {message}");

    let error = load(HEADER, ENV, &MARKS.replace("label", "labl"))
        .expect_err("an unknown field is not a chunk either");
    assert!(
        matches!(&error, ScnError::Parse { key, .. } if key == "one.scn/sys/marks.ron"),
        "{error}"
    );
}

/// **A chunk file that is not this system's is refused rather than
/// attached.** The file name and the `system` field are two statements of
/// the same thing, and a copied file is where they disagree.
#[test]
fn a_chunk_declaring_another_system_is_refused() {
    let error = load(HEADER, ENV, &MARKS.replace("\"marks\"", "\"props\""))
        .expect_err("that chunk belongs to another system");
    assert!(
        matches!(&error, ScnError::Chunk { key, declared, expected }
            if key == "one.scn/sys/marks.ron" && declared == "props" && expected == "marks"),
        "{error}"
    );
}

/// **A manifest entry with no codec stops the load.** Skipping it would
/// produce a world missing a third of its entities and no way to tell.
#[test]
fn a_manifest_system_with_no_codec_is_refused_by_name() {
    let source = source(HEADER, ENV, MARKS);
    let mut world = world_with_marks();
    let error = Scene::load(&source, Path::new("one.scn"), &[], &mut world)
        .expect_err("no codec was registered for `marks`");
    assert!(
        matches!(&error, ScnError::NoCodec { system } if system == "marks"),
        "{error}"
    );
}

/// **A codec with no system in the world is refused too.** The mirror of
/// the case above, and the one a caller hits by forgetting
/// `register_system`.
#[test]
fn a_codec_with_no_system_in_the_world_is_refused() {
    let source = source(HEADER, ENV, MARKS);
    let mut world = World::new();
    let error = Scene::load(&source, Path::new("one.scn"), &codecs(), &mut world)
        .expect_err("the world holds no `marks`");
    assert!(
        matches!(&error, ScnError::NoSystem { system, .. } if system == "marks"),
        "{error}"
    );
}

/// **One id, one row per chunk.** Two rows of one chunk claiming the same id
/// would be two components of one system for one entity, and the second would
/// silently replace the first.
#[test]
fn a_repeated_scene_entity_id_is_refused() {
    let doubled = MARKS.replace(
        "    ],\n)",
        "        (0, Mark(\n            position: (2.0, 0.0, 0.0),\n            label: \"second\",\n        )),\n    ],\n)",
    );
    let error = load(HEADER, ENV, &doubled).expect_err("id 0 is claimed twice");
    assert!(
        matches!(&error, ScnError::DuplicateId { key, id }
            if key == "one.scn/sys/marks.ron" && *id == SceneEntityId(0)),
        "{error}"
    );
}

/// **An entity with no id is refused rather than dropped.** The writer has
/// nowhere to file it, and a save that quietly shrank the scene is the
/// failure worth being loud about; [`IdMap::assign`] is the fix.
#[test]
fn saving_an_entity_that_never_got_an_id_is_refused() {
    let (scene, mut ids, mut world) = load(HEADER, ENV, MARKS).expect("the scene loads");
    let stray = world.spawn();
    let marks = system_named::<Mark>(&mut world, "marks").expect("the world holds it");
    marks.attach(
        stray,
        Mark {
            position: [0.0; 3],
            label: "stray".to_string(),
        },
    );

    let error = scene
        .save(&mut world, &ids, &codecs())
        .expect_err("the stray has no scene id");
    assert!(
        matches!(&error, ScnError::NoSceneId { system, .. } if system == "marks"),
        "{error}"
    );

    // Give it one and the same save succeeds, with the id after the file's.
    assert_eq!(ids.assign(stray), SceneEntityId(1));
    assert_eq!(ids.assign(stray), SceneEntityId(1), "assign is idempotent");
    let files = scene
        .save(&mut world, &ids, &codecs())
        .expect("every entity has an id now");
    assert!(files["sys/marks.ron"].contains("stray"));
    assert_eq!(ids.entity(SceneEntityId(1)), Some(stray));
    assert_eq!(ids.id(stray), Some(SceneEntityId(1)));
}

/// **A key that is not there says so, and says which key.**
#[test]
fn a_directory_with_no_header_names_the_key_it_wanted() {
    let source = MemorySource::new();
    let mut world = world_with_marks();
    let error = Scene::load(&source, Path::new("one.scn"), &codecs(), &mut world)
        .expect_err("there is no scene there");
    assert!(
        matches!(&error, ScnError::Read { key, source: StorageError::NotFound(_) }
            if key == "one.scn/scene.ron"),
        "{error}"
    );
}

/// **A source rooted at the scene directory itself loads.** `.` and the
/// empty path both mean "here", which is what a `DirSource::at(scene_dir)`
/// hands over. The empty one is the case with a branch behind it: joining
/// it would produce `/scene.ron`, whose leading empty component every
/// source refuses. `.` is carried by `canonical_key` dropping the
/// component, which is why `join_key` has no arm for it.
#[test]
fn a_scene_directory_that_is_the_source_root_loads() {
    let mut source = MemorySource::new();
    for (key, text) in [
        ("scene.ron", HEADER),
        ("env.ron", ENV),
        ("sys/marks.ron", MARKS),
    ] {
        source
            .insert(Path::new(key), text.as_bytes().to_vec())
            .expect("a legal asset key");
    }
    for dir in [".", ""] {
        let mut world = world_with_marks();
        let (scene, ids) = Scene::load(&source, Path::new(dir), &codecs(), &mut world)
            .unwrap_or_else(|error| panic!("`{dir}` is the source root: {error}"));
        assert_eq!(scene.name(), "one");
        assert_eq!(ids.len(), 1);
    }
}

/// **A scene built in code writes the same file a loaded one does**, which
/// is what lets a sample's committed chunk be generated rather than typed.
#[test]
fn a_scene_built_in_code_writes_the_canonical_files() {
    let mut world = world_with_marks();
    let mut ids = IdMap::new();
    let entity = world.spawn();
    assert_eq!(ids.assign(entity), SceneEntityId(0));
    system_named::<Mark>(&mut world, "marks")
        .expect("the world holds it")
        .attach(
            entity,
            Mark {
                position: [1.0, 0.0, -1.0],
                label: "first".to_string(),
            },
        );

    let mut scene = Scene::new(
        "one",
        vec!["marks".to_string()],
        Env {
            camera: EnvCamera {
                position: [0.0, 2.0, 8.0],
                look_at: [0.0; 3],
            },
            ambient: [0.05, 0.05, 0.08],
        },
    );
    let files = scene
        .save(&mut world, &ids, &codecs())
        .expect("the world matches the manifest");
    assert_eq!(files["scene.ron"], HEADER);
    assert_eq!(files["env.ron"], ENV);
    assert_eq!(files["sys/marks.ron"], MARKS);

    scene.env_mut().ambient = [0.0; 3];
    assert_eq!(scene.env().ambient, [0.0; 3]);
    assert_ne!(
        scene
            .save(&mut world, &ids, &codecs())
            .expect("still writable")["env.ron"],
        ENV
    );
}

/// The debug form names the system and the component, so a codec list is
/// readable in a panic message.
#[test]
fn a_codecs_debug_output_names_its_system_and_component() {
    let text = format!("{:?}", chunk_of::<Mark>("marks"));
    assert!(text.contains("marks"), "{text}");
    assert!(text.contains("Mark"), "{text}");
}

/// **A removed id comes back under the same id, and is never handed out in
/// between** — the property an undone delete needs, since a later command
/// in the history still names it.
#[test]
fn a_removed_id_is_restored_and_never_reassigned() {
    let (_, mut ids, mut world) = load(HEADER, ENV, MARKS).expect("the canonical scene loads");
    let first = ids.entity(SceneEntityId(0)).expect("the file's one row");
    assert_eq!(ids.next_id(), SceneEntityId(1));

    assert_eq!(ids.remove(SceneEntityId(0)), Some(first));
    assert_eq!(ids.entity(SceneEntityId(0)), None);
    assert_eq!(ids.id(first), None);
    assert_eq!(ids.remove(SceneEntityId(0)), None, "already gone");

    let other = world.spawn();
    assert_eq!(
        ids.assign(other),
        SceneEntityId(1),
        "a removed id is not handed out again",
    );
    assert!(
        !ids.restore(SceneEntityId(1), first),
        "an id in use is not taken over",
    );
    assert!(
        !ids.restore(SceneEntityId(0), other),
        "an entity with an id is not filed twice",
    );
    assert!(ids.restore(SceneEntityId(0), first));
    assert_eq!(ids.entity(SceneEntityId(0)), Some(first));
    assert_eq!(ids.id(first), Some(SceneEntityId(0)));
    assert_eq!(ids.len(), 2);
}

/// Restoring an id past the high-water mark raises it, so the next
/// [`IdMap::assign`] does not hand the same id out twice.
#[test]
fn restoring_the_next_id_moves_the_mark_past_it() {
    let mut world = World::new();
    let mut ids = IdMap::new();
    let next = ids.next_id();
    let spawned = world.spawn();
    assert!(ids.restore(next, spawned));
    assert_ne!(ids.assign(world.spawn()), next);
}

/// **A reserved mark survives a reload's lower one**: a map read back from
/// files that no longer spell a removed id hands out neither it nor
/// anything below the mark — and reserving below the mark moves nothing.
#[test]
fn a_reserved_mark_is_not_handed_out_again() {
    let (_, mut ids, mut world) = load(HEADER, ENV, MARKS).expect("the canonical scene loads");
    assert_eq!(ids.next_id(), SceneEntityId(1), "the file holds id 0");

    ids.reserve(SceneEntityId(4));
    assert_eq!(ids.next_id(), SceneEntityId(4));
    assert_eq!(ids.assign(world.spawn()), SceneEntityId(4));

    ids.reserve(SceneEntityId(2));
    assert_eq!(
        ids.next_id(),
        SceneEntityId(5),
        "a lower reservation moved the mark"
    );
}

/// **A row round-trips one component exactly**, which is what a deleted
/// entity's undo is rebuilt from.
#[test]
fn a_row_attaches_back_as_the_component_it_was_read_from() {
    let (_, ids, mut world) = load(HEADER, ENV, MARKS).expect("the canonical scene loads");
    let codec = chunk_of::<Mark>("marks");
    let first = ids.entity(SceneEntityId(0)).expect("the file's one row");
    let row = codec
        .row(&mut world, first)
        .expect("the system is registered")
        .expect("the system holds the file's row");

    let copy = world.spawn();
    codec
        .attach_row(&mut world, copy, &row)
        .expect("a row reads back");
    let system = world.system_mut::<System<Mark>>().expect("registered");
    assert_eq!(system.get(copy), system.get(first));
    assert_eq!(
        system.get(copy).map(|mark| mark.label.as_str()),
        Some("first"),
    );

    let stranger = world.spawn();
    assert_eq!(
        codec.row(&mut world, stranger).expect("registered"),
        None,
        "an entity the system does not hold has no row",
    );
}

/// The canonical scene's header, declaring a names file.
fn named_header() -> String {
    HEADER.replace("    ],\n)", "    ],\n    names: true,\n)")
}

/// The canonical names file: the one row, named.
const NAMES: &str = "Names(\n    names: [\n        (0, \"Gate\"),\n    ],\n)";

/// [`load`], with `names` at `one.scn/names.ron` beside the trio.
fn load_named(header: &str, names: &str) -> Result<(Scene, IdMap, World), ScnError> {
    let mut source = source(header, ENV, MARKS);
    source
        .insert(Path::new("one.scn/names.ron"), names.as_bytes().to_vec())
        .expect("a nested scene key is a legal asset key");
    let mut world = world_with_marks();
    let (scene, ids) = Scene::load(&source, Path::new("one.scn"), &codecs(), &mut world)?;
    Ok((scene, ids, world))
}

/// **A named scene round-trips byte for byte**, its header declaring the
/// names file — and a scene whose last name is taken away writes neither
/// the file nor the declaration, so it is the unnamed scene again.
#[test]
fn names_round_trip_and_vanish_when_the_last_goes() {
    let (mut scene, ids, mut world) =
        load_named(&named_header(), NAMES).expect("the named scene loads");
    assert_eq!(
        scene.entity_name(SceneEntityId(0)).map(EntityName::as_str),
        Some("Gate"),
    );
    let files = scene
        .save(&mut world, &ids, &codecs())
        .expect("a scene that loaded can be written");
    assert_eq!(files["scene.ron"], named_header());
    assert_eq!(files["names.ron"], NAMES);
    assert_eq!(files["sys/marks.ron"], MARKS);

    let was = scene.set_entity_name(SceneEntityId(0), None);
    assert_eq!(was.as_ref().map(EntityName::as_str), Some("Gate"));
    let files = scene
        .save(&mut world, &ids, &codecs())
        .expect("still writable");
    assert_eq!(
        files["scene.ron"], HEADER,
        "the header still declares names"
    );
    assert_eq!(
        files.keys().collect::<Vec<_>>(),
        ["env.ron", "scene.ron", "sys/marks.ron"],
        "a scene with no names still writes the names file",
    );
}

/// **Names are written in id order whatever order they were given in**,
/// so two scenes holding the same names write the same file.
#[test]
fn names_are_written_in_id_order() {
    let (mut scene, mut ids, mut world) = load(HEADER, ENV, MARKS).expect("the scene loads");
    let second = world.spawn();
    assert_eq!(ids.assign(second), SceneEntityId(1));
    system_named::<Mark>(&mut world, "marks")
        .expect("registered")
        .attach(
            second,
            Mark {
                position: [0.0; 3],
                label: "second".to_owned(),
            },
        );
    let name = |text| Some(EntityName::new(text).expect("a name"));
    scene.set_entity_name(SceneEntityId(1), name("Spawner"));
    scene.set_entity_name(SceneEntityId(0), name("Gate"));
    let files = scene.save(&mut world, &ids, &codecs()).expect("writable");
    assert_eq!(
        files["names.ron"],
        "Names(\n    names: [\n        (0, \"Gate\"),\n        (1, \"Spawner\"),\n    ],\n)",
    );
}

/// **A name for an id the scene does not hold is refused by that id**, on
/// load and on save — a save would otherwise write a file its own loader
/// refuses.
#[test]
fn a_name_for_an_id_the_scene_does_not_hold_is_refused() {
    let error = load_named(&named_header(), &NAMES.replace("(0,", "(7,"))
        .expect_err("id 7 is not in the scene");
    assert!(
        matches!(&error, ScnError::NameOfNoEntity { key, id }
            if key == "one.scn/names.ron" && *id == SceneEntityId(7)),
        "{error}"
    );

    let (mut scene, ids, mut world) = load(HEADER, ENV, MARKS).expect("the scene loads");
    scene.set_entity_name(
        SceneEntityId(7),
        Some(EntityName::new("Ghost").expect("a name")),
    );
    let error = scene
        .save(&mut world, &ids, &codecs())
        .expect_err("id 7 is not in the scene");
    assert!(
        matches!(&error, ScnError::NameOfNoEntity { id, .. } if *id == SceneEntityId(7)),
        "{error}"
    );
}

/// **Text that is not a name is refused by the rule it breaks and the id
/// it was for**: empty, too long, and a control character.
#[test]
fn a_names_file_holding_text_that_is_not_a_name_is_refused() {
    let long = "n".repeat(MAX_NAME_CHARS + 1);
    for (text, expected) in [
        ("   ", NameError::Empty),
        (
            long.as_str(),
            NameError::TooLong {
                chars: MAX_NAME_CHARS + 1,
            },
        ),
        ("Ga\\tte", NameError::Control('\t')),
    ] {
        let names = NAMES.replace("\"Gate\"", &format!("\"{text}\""));
        let error = load_named(&named_header(), &names).expect_err("not a name");
        assert!(
            matches!(&error, ScnError::Name { key, id, error }
                if key == "one.scn/names.ron" && *id == SceneEntityId(0)
                    && *error == expected),
            "{text:?}: {error}"
        );
    }
}

/// One id named twice, a declared file that names nothing, a declared file
/// that is not there, and a field the file does not have are each refused.
#[test]
fn a_names_file_that_disagrees_with_itself_or_the_header_is_refused() {
    let twice = NAMES.replace("    ],\n)", "        (0, \"Again\"),\n    ],\n)");
    let error = load_named(&named_header(), &twice).expect_err("0 is named twice");
    assert!(
        matches!(&error, ScnError::DuplicateId { key, id }
            if key == "one.scn/names.ron" && *id == SceneEntityId(0)),
        "{error}"
    );

    let error = load_named(&named_header(), "Names(names: [])").expect_err("names nothing");
    assert!(matches!(&error, ScnError::NoNames { .. }), "{error}");

    let error = load(&named_header(), ENV, MARKS).expect_err("the names file is missing");
    assert!(
        matches!(&error, ScnError::Read { key, source: StorageError::NotFound(_) }
            if key == "one.scn/names.ron"),
        "{error}"
    );

    let error = load_named(&named_header(), &NAMES.replace("names:", "nams:"))
        .expect_err("an unknown field");
    assert!(
        matches!(&error, ScnError::Parse { key, .. } if key == "one.scn/names.ron"),
        "{error}"
    );
}

/// **A names file the header does not declare is not read**: the header is
/// what says which files the scene is, and an undeclared one is not part of
/// it — so a save writes the scene without it.
#[test]
fn a_names_file_the_header_does_not_declare_is_not_read() {
    let (scene, ids, mut world) =
        load_named(HEADER, "not even RON").expect("an undeclared file is not read");
    assert!(scene.entity_names().is_empty());
    let files = scene.save(&mut world, &ids, &codecs()).expect("writable");
    assert!(!files.contains_key("names.ron"));
}

/// Text that is not the component is refused by the system's name, and
/// nothing is attached.
#[test]
fn a_row_that_is_not_the_component_is_refused_and_attaches_nothing() {
    let mut world = world_with_marks();
    let codec = chunk_of::<Mark>("marks");
    let entity = world.spawn();
    let error = codec
        .attach_row(&mut world, entity, "Mark(position: (1.0, 2.0, 3.0))")
        .expect_err("a mark has a label");
    assert!(
        matches!(&error, ScnError::Parse { key, .. } if key == "marks"),
        "{error}",
    );
    let system = world.system_mut::<System<Mark>>().expect("registered");
    assert!(system.get(entity).is_none());
}

/// A second system's component, so a scene can hold one entity in two
/// systems of two different types.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
struct Tag {
    weight: u32,
}

impl ComponentHash for Tag {
    fn hash_component(&self, hasher: &mut dyn Hasher) {
        hasher.write_u32(self.weight);
    }
}

/// The canonical scene's header, listing `marks` and then `tags`.
fn two_system_header() -> String {
    HEADER.replace(
        "\"marks\",
",
        "\"marks\",
        \"tags\",
",
    )
}

/// A `tags` chunk: id 0 — the marks chunk's one row — and id 5, which no
/// other chunk spells.
const TAGS: &str = "Chunk(
    system: \"tags\",
    entities: [
        (0, Tag(
            weight: 3,
        )),
        (5, Tag(
            weight: 9,
        )),
    ],
)";

fn two_system_codecs() -> Vec<Box<dyn SystemChunk>> {
    vec![chunk_of::<Mark>("marks"), chunk_of::<Tag>("tags")]
}

/// [`load`], with `tags` registered and its chunk at `one.scn/sys/tags.ron`.
fn load_two(header: &str, tags: &str) -> Result<(Scene, IdMap, World), ScnError> {
    let mut source = source(header, ENV, MARKS);
    source
        .insert(Path::new("one.scn/sys/tags.ron"), tags.as_bytes().to_vec())
        .expect("a nested scene key is a legal asset key");
    let mut world = world_with_marks();
    world.register_system(Box::new(System::<Tag>::new("tags")));
    let (scene, ids) = Scene::load(
        &source,
        Path::new("one.scn"),
        &two_system_codecs(),
        &mut world,
    )?;
    Ok((scene, ids, world))
}

/// **An id spelled by two chunks is one entity holding both components**, and
/// the scene writes back byte for byte — each system's row in its own chunk.
#[test]
fn an_id_in_two_chunks_is_one_entity_in_both_systems() {
    let (scene, ids, mut world) =
        load_two(&two_system_header(), TAGS).expect("one entity in two systems is a scene");
    assert_eq!(ids.len(), 2, "ids 0 and 5, not three entities");
    let both = ids.entity(SceneEntityId(0)).expect("id 0");
    let tagged = ids.entity(SceneEntityId(5)).expect("id 5");
    assert_ne!(both, tagged);

    let marks = world.system_mut::<System<Mark>>().expect("registered");
    assert_eq!(
        marks.get(both).map(|mark| mark.label.as_str()),
        Some("first"),
    );
    assert!(marks.get(tagged).is_none(), "5 has no mark");
    let tags = world.system_mut::<System<Tag>>().expect("registered");
    assert_eq!(tags.get(both), Some(&Tag { weight: 3 }));
    assert_eq!(tags.get(tagged), Some(&Tag { weight: 9 }));
    assert_eq!(
        world.entity_count(),
        2,
        "a second entity was spawned for id 0"
    );

    let files = scene
        .save(&mut world, &ids, &two_system_codecs())
        .expect("a scene that loaded can be written");
    assert_eq!(files["scene.ron"], two_system_header());
    assert_eq!(files["sys/marks.ron"], MARKS);
    assert_eq!(files["sys/tags.ron"], TAGS);
}

/// **The same id twice in one chunk is still refused**, though the same id in
/// two chunks is not — the check is the chunk's, not the map's.
#[test]
fn an_id_twice_in_one_chunk_of_a_two_system_scene_is_refused() {
    let doubled = TAGS.replace("(5, Tag(", "(0, Tag(");
    let error = load_two(&two_system_header(), &doubled).expect_err("0 is tagged twice");
    assert!(
        matches!(&error, ScnError::DuplicateId { key, id }
            if key == "one.scn/sys/tags.ron" && *id == SceneEntityId(0)),
        "{error}"
    );
}

/// **A manifest naming a system twice is refused by the header and the
/// system**, before any chunk is read over itself.
#[test]
fn a_manifest_naming_a_system_twice_is_refused() {
    let twice = HEADER.replace(
        "\"marks\",
",
        "\"marks\",
        \"marks\",
",
    );
    let error = load(&twice, ENV, MARKS).expect_err("marks is listed twice");
    assert!(
        matches!(&error, ScnError::RepeatedSystem { key, system }
            if key == "one.scn/scene.ron" && system == "marks"),
        "{error}"
    );
}

/// **A detached row is the component's row, and the entity keeps every other
/// system's**: detaching from a system that does not hold it changes nothing,
/// and the row attaches back to the same scene text.
#[test]
fn a_detached_row_leaves_the_entity_and_attaches_back() {
    let (scene, ids, mut world) = load_two(&two_system_header(), TAGS).expect("the scene loads");
    let both = ids.entity(SceneEntityId(0)).expect("id 0");
    let tagged = ids.entity(SceneEntityId(5)).expect("id 5");
    let marks = chunk_of::<Mark>("marks");
    let before = scene
        .save(&mut world, &ids, &two_system_codecs())
        .expect("writable");

    assert_eq!(
        marks.detach_row(&mut world, tagged).expect("registered"),
        None,
        "a system that does not hold the entity detached something",
    );
    let row = marks
        .detach_row(&mut world, both)
        .expect("registered")
        .expect("marks holds id 0");
    assert_eq!(
        row,
        row_text(
            "marks",
            &Mark {
                position: [1.0, 0.0, -1.0],
                label: "first".to_owned(),
            },
        )
        .expect("a mark serializes"),
    );
    assert!(world.is_alive(both), "a detach despawned the entity");
    assert!(
        world
            .system_mut::<System<Mark>>()
            .expect("registered")
            .get(both)
            .is_none()
    );
    assert_eq!(
        world
            .system_mut::<System<Tag>>()
            .expect("registered")
            .get(both),
        Some(&Tag { weight: 3 }),
        "a detach from marks took the tag too",
    );
    let detached = scene
        .save(&mut world, &ids, &two_system_codecs())
        .expect("writable");
    assert!(!detached["sys/marks.ron"].contains("(0, Mark("));
    assert_eq!(detached["sys/tags.ron"], before["sys/tags.ron"]);

    marks
        .attach_row(&mut world, both, &row)
        .expect("its own row reads back");
    assert_eq!(
        scene
            .save(&mut world, &ids, &two_system_codecs())
            .expect("writable"),
        before,
    );
}

/// **Listing a system adds its chunk to the next save, and unlisting it puts
/// the files back as they were**; listing one twice or unlisting one never
/// listed changes nothing.
#[test]
fn a_listed_system_is_saved_and_unlisting_it_restores_the_files() {
    let (mut scene, ids, mut world) = load(HEADER, ENV, MARKS).expect("the canonical scene loads");
    world.register_system(Box::new(System::<Mark>::new("pins")));
    let codecs = vec![chunk_of::<Mark>("marks"), chunk_of::<Mark>("pins")];
    let before = scene.save(&mut world, &ids, &codecs).expect("saves");

    assert!(scene.list_system("pins"));
    assert!(!scene.list_system("pins"), "a system was listed twice");
    assert_eq!(scene.systems(), ["marks", "pins"]);
    let listed = scene.save(&mut world, &ids, &codecs).expect("saves");
    assert_eq!(
        listed["sys/pins.ron"],
        "Chunk(\n    system: \"pins\",\n    entities: [],\n)"
    );
    assert!(
        listed["scene.ron"].contains("\"pins\""),
        "{}",
        listed["scene.ron"]
    );

    assert!(scene.unlist_system("pins"));
    assert!(
        !scene.unlist_system("pins"),
        "an unlisted system was unlisted"
    );
    assert_eq!(
        scene.save(&mut world, &ids, &codecs).expect("saves"),
        before
    );
}
