//! This crate's console table, held to this crate's source.
//!
//! Plan decision 2's second half, written here exactly as
//! `crates/crcbl-core/tests/console_table.rs` writes it: a command declared
//! beside the behaviour it drives is only reachable once it is in the crate's
//! one list, and nothing but this makes the list keep up. Forgetting it is then
//! a red test rather than a command that quietly does not exist.

/// **Every `concommand!` and `convar!` in `crates/crcbl/src` is in
/// [`crcbl::console_table`].**
#[test]
fn every_console_declaration_in_this_crate_is_in_its_table() {
    let declared = crcbl_console::guard::declared_names("src").expect("this crate's src directory");
    // A scan that matched nothing would report success forever, so the scan is
    // held to something it must have found: `quit` is declared in
    // `src/debug_console.rs`, and its absence means the walk did not reach that
    // file rather than that the crate declares nothing.
    assert!(
        declared.contains(&"quit".to_owned()),
        "the scan did not reach `debug_console.rs`: {declared:?}",
    );

    let table = crcbl::console_table();
    for name in &declared {
        assert!(
            table
                .commands()
                .iter()
                .any(|command| command.name() == name)
                || table.vars().iter().any(|var| var.name() == name)
                || table.bindings().iter().any(|bound| bound.name() == name),
            "`{name}` is declared in this crate's source and missing from its table",
        );
    }
}

/// **Every catalogue key is in the table too**, through
/// `settings::console_bindings` — so "the console exposes every setting the
/// engine reads" is a check rather than a claim.
///
/// The source guard above cannot see these: a binding is generated by a macro
/// from the catalogue rather than declared with `convar!`, which is the whole
/// point of plan decision 3.
#[test]
fn every_settings_key_is_a_variable_in_the_table() {
    let table = crcbl::console_table();
    let catalogue = crcbl::settings::catalogue();
    assert!(
        !catalogue.is_empty(),
        "an empty catalogue would make this pass over an empty table"
    );
    for key in &catalogue {
        assert!(
            table
                .bindings()
                .iter()
                .any(|bound| bound.name() == key.name),
            "`{}` is a settings key the console cannot reach",
            key.name,
        );
    }
}
