//! Bakes `assets/*.crpix` into the PNG + Aseprite-sidecar pair the engine
//! reads, and generates the table `src/art.rs` includes.
//!
//! ```text
//! assets/bird.crpix ──parse──▶ CrpixArt ──bake──▶ $OUT_DIR/bird.png
//!                                              └─▶ $OUT_DIR/bird.json
//!                                    │
//!                                    └──▶ $OUT_DIR/art_data.rs  (include_bytes!)
//! ```
//!
//! # Why the baked files are not committed
//!
//! `docs/specs/crcbl/pix.md` is explicit that `.crpix` is a **build input** and
//! that nothing downstream knows it exists. Committing the PNG beside the text
//! would create two sources of truth for the same picture, and the one a
//! reviewer reads in a diff would be the one that is not loaded. Baking here
//! means the text is the art: edit it, and the next build regenerates
//! everything derived from it.
//!
//! # Why a generated table rather than four `include_bytes!` written by hand
//!
//! Because whether a sheet *has* a sidecar is a property of the art, not of the
//! game: [`crcbl_sprite::crpix::CrpixArt::needs_metadata`] says no for a single
//! still frame with no clips and no nine-slice, which is what `hills` and
//! `ground` are today and is not what they have to stay. A hand-written
//! `include_str!("…/hills.json")` would fail to compile the day someone adds a
//! clip's worth of animation to a background — or, worse, keep compiling
//! against a stale file. The script that knows the answer writes it down.
//!
//! # This runs on the host, for every target
//!
//! `apps/flappy` builds for `wasm32-unknown-unknown`, and a build script is
//! compiled and run for the *host* whatever the target is. That is what makes
//! this legal: the browser build gets the same bytes, already baked, through
//! `include_bytes!`, and nothing reads a file at runtime on any target.

use std::path::{Path, PathBuf};

/// The tick rate the frame holds are baked against.
///
/// A `.crpix` counts holds in **simulation ticks** and an Aseprite sidecar
/// counts milliseconds, so the pair has to be converted on the way out and back
/// on the way in — and the two conversions must use the same rate or every
/// hold changes. `src/art.rs`'s `ART_TICK_HZ` is the other half, and
/// `the_art_bakes_to_the_sheets_it_declares` asserts the authored hold survives,
/// which is the check that catches the two drifting apart.
const ART_TICK_HZ: u32 = 60;

/// The sheets, by file stem. Each is `assets/<stem>.crpix`.
const ASSETS: [&str; 4] = ["bird", "pipe", "hills", "ground"];

fn main() {
    let root = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("cargo always sets CARGO_MANIFEST_DIR"),
    );
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("cargo always sets OUT_DIR"));

    let mut table = String::from(
        "// @generated by build.rs from apps/flappy/assets/*.crpix — do not edit.\n\n",
    );

    for stem in ASSETS {
        let relative = format!("assets/{stem}.crpix");
        // **The line that makes editing art rebuild the game.** Without it the
        // baked PNG in OUT_DIR is a cached artifact of a source cargo has never
        // been told about, and a redrawn wing shows up on the next `cargo
        // clean` and not before.
        println!("cargo::rerun-if-changed={relative}");

        let source = root.join(&relative);
        let text = std::fs::read_to_string(&source)
            .unwrap_or_else(|error| fail(&format!("{relative}: {error}")));
        let art = crcbl_sprite::crpix::parse(&text)
            .unwrap_or_else(|error| fail(&format!("{relative}:{error}")));

        let image = format!("{stem}.png");
        let baked = crcbl_sprite::bake::bake(&art, &image, ART_TICK_HZ)
            .unwrap_or_else(|error| fail(&format!("{relative}: {error}")));

        let png = out.join(&image);
        write(&png, &baked.png);
        let upper = stem.to_uppercase();
        table.push_str(&format!(
            "pub static {upper}_PNG: &[u8] = include_bytes!({:?});\n",
            png.display().to_string()
        ));

        match &baked.json {
            Some(json) => {
                let sidecar = out.join(format!("{stem}.json"));
                write(&sidecar, json.as_bytes());
                table.push_str(&format!(
                    "pub static {upper}_JSON: Option<&str> = Some(include_str!({:?}));\n",
                    sidecar.display().to_string()
                ));
            }
            // A single still frame is fully described by its image; the loader
            // takes `None` and reads one frame covering the whole picture.
            None => table.push_str(&format!("pub static {upper}_JSON: Option<&str> = None;\n")),
        }
    }

    write(&out.join("art_data.rs"), table.as_bytes());
}

fn write(path: &Path, bytes: &[u8]) {
    std::fs::write(path, bytes)
        .unwrap_or_else(|error| fail(&format!("writing {}: {error}", path.display())));
}

/// Fails the build with a message cargo shows, rather than a panic backtrace.
fn fail(message: &str) -> ! {
    println!("cargo::error={message}");
    std::process::exit(1);
}
