//! Turning a [`Protocol`] into Rust.
//!
//! # Shape of the emitted code
//!
//! One module per protocol file, one module per interface inside it:
//!
//! ```text
//! pub mod wayland {
//!     static TYPES: [WlInterfacePtr; 97] = [ … ];    // the protocol's type table
//!     pub mod wl_surface {
//!         pub const NAME: &CStr;  pub const VERSION: u32;
//!         pub const REQ_ATTACH: u32 = 1;  pub const EVT_ENTER: u32 = 0;
//!         pub static INTERFACE: WlInterface;         // the wl_interface descriptor
//!         pub unsafe fn attach(proxy, buffer, x, y); // request wrapper
//!         pub enum Event<'a> { … }                   // typed events
//!         pub unsafe fn decode_event(opcode, args) -> Option<Event<'_>>;
//!         pub mod error { pub const INVALID_SCALE: u32 = 0; }
//!     }
//! }
//! ```
//!
//! Cross-protocol references resolve by interface name, which is what lets
//! `xdg-shell`'s type table point at `wayland`'s `wl_surface` without either
//! file knowing about the other. Adding a protocol to the build is therefore
//! one line in the caller's list, never an edit here — the property
//! `docs/plan/15-windowing.md`'s P0.5b/c slices (`wl_seat`, `xdg-decoration`,
//! `data-device`) depend on.
//!
//! # The part that has to be exactly right
//!
//! `wl_message.signature` and the `wl_message.types` table are read by
//! libwayland *and by the graphics driver's WSI code* to encode and decode
//! every message on the socket. A wrong character or a shifted index does not
//! fail to compile and does not raise a protocol error — it writes the wrong
//! bytes and misreads the reply. So both are generated by the same rules
//! `wayland-scanner` uses, and this crate's tests compare the output against
//! `wayland-scanner`'s own for real interfaces rather than against our idea of
//! what it should be.

use core::fmt::Write as _;

use crate::model::{Arg, ArgType, Interface, Message, Protocol};

/// How to generate: where the runtime facade lives.
#[derive(Clone, Debug)]
pub struct Options<'a> {
    /// Path to the module providing `WlArgument`, `WlArray`, `WlInterface`,
    /// `WlInterfacePtr`, `WlMessage`, `WlProxy`, `marshal`, `proxy_version`,
    /// `cstr_arg`, `cstr_arg_opt` and `array_arg`.
    ///
    /// An absolute path rather than a `use`, so the generated file can be
    /// `include!`d at any depth without guessing how many `super`s it needs.
    pub ffi_path: &'a str,
}

impl Default for Options<'_> {
    fn default() -> Self {
        Self {
            ffi_path: "crate::wayland::ffi",
        }
    }
}

/// One protocol file to generate from.
#[derive(Clone, Debug)]
pub struct Source<'a> {
    /// Rust module name to emit it as, e.g. `"wayland"`, `"xdg_shell"`.
    pub module: &'a str,
    /// The parsed protocol.
    pub protocol: Protocol,
}

/// An interface an argument referred to is in none of the given protocols.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct EmitError {
    /// The interface that could not be resolved.
    pub interface: String,
    /// Where it was referred to, as `protocol::interface::message`.
    pub referenced_by: String,
}

impl core::fmt::Display for EmitError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(
            f,
            "{} refers to interface {:?}, which is in none of the given protocol files",
            self.referenced_by, self.interface
        )
    }
}

impl std::error::Error for EmitError {}

const HEADER: &str = "\
// @generated by crcbl-wl-scanner. Do not edit.
//
// Regenerated on every build from the protocol XML vendored in
// `crates/crcbl-shell/wayland-protocols/`; see that directory's README for the
// upstream versions.
";

/// Emits one Rust file covering every protocol in `sources`.
///
/// Module order follows `sources`; interface resolution spans the whole set, so
/// a protocol may refer forwards to one listed after it.
///
/// # Errors
///
/// [`EmitError`] when an argument names an interface that appears in none of
/// the protocols. That is a missing XML file, and emitting a null pointer in
/// its place would produce a marshaller that mis-encodes the wire rather than
/// one that fails to build.
pub fn emit(sources: &[Source<'_>], options: &Options<'_>) -> Result<String, EmitError> {
    let index = InterfaceIndex::build(sources);
    let mut out = String::with_capacity(512 * 1024);
    out.push_str(HEADER);
    for source in sources {
        emit_protocol(&mut out, source, &index, options)?;
    }
    Ok(out)
}

/// Interface name → `protocol_module::interface_module`, across every source.
struct InterfaceIndex {
    entries: Vec<(String, String)>,
}

impl InterfaceIndex {
    fn build(sources: &[Source<'_>]) -> Self {
        let mut entries = Vec::new();
        for source in sources {
            for interface in &source.protocol.interfaces {
                entries.push((
                    interface.name.clone(),
                    format!("{}::{}", source.module, interface.name),
                ));
            }
        }
        Self { entries }
    }

    fn path(&self, name: &str) -> Option<&str> {
        self.entries
            .iter()
            .find(|(candidate, _)| candidate == name)
            .map(|(_, path)| path.as_str())
    }
}

/// Every message of an interface in opcode order, requests before events —
/// the order the type table is laid out in.
fn messages(interface: &Interface) -> impl Iterator<Item = &Message> {
    interface.requests.iter().chain(&interface.events)
}

/// The length of the shared leading null run: the widest message in the
/// protocol whose arguments name no interface.
fn null_run_length(protocol: &Protocol) -> usize {
    protocol
        .interfaces
        .iter()
        .flat_map(messages)
        .filter(|message| message.all_null())
        .map(|message| message.type_slots().len())
        .max()
        .unwrap_or(0)
}

/// The protocol's flat type table, plus each message's offset into it.
///
/// Reproduces `wayland-scanner`'s layout exactly: the leading null run, which
/// every all-null message points at, followed by one row per message that names
/// an interface, in interface-then-opcode order.
fn type_table(
    protocol: &Protocol,
    index: &InterfaceIndex,
) -> Result<(Vec<Option<String>>, Vec<usize>), EmitError> {
    let mut table: Vec<Option<String>> = vec![None; null_run_length(protocol)];
    let mut offsets = Vec::new();
    for interface in &protocol.interfaces {
        for message in messages(interface) {
            if message.all_null() {
                offsets.push(0);
                continue;
            }
            offsets.push(table.len());
            for slot in message.type_slots() {
                match slot {
                    None => table.push(None),
                    Some(name) => {
                        let path = index.path(name).ok_or_else(|| EmitError {
                            interface: name.to_string(),
                            referenced_by: format!(
                                "{}::{}::{}",
                                protocol.name, interface.name, message.name
                            ),
                        })?;
                        table.push(Some(path.to_string()));
                    }
                }
            }
        }
    }
    // A protocol whose messages take no arguments at all would produce an empty
    // table, and `&TYPES[0]` would then not compile. One null entry is
    // byte-equivalent: every offset is 0 and no message reads a slot.
    if table.is_empty() {
        table.push(None);
    }
    Ok((table, offsets))
}

fn emit_protocol(
    out: &mut String,
    source: &Source<'_>,
    index: &InterfaceIndex,
    options: &Options<'_>,
) -> Result<(), EmitError> {
    let module = source.module;
    let ffi = options.ffi_path;
    let (table, offsets) = type_table(&source.protocol, index)?;

    let _ = writeln!(
        out,
        "\n/// The `{}` protocol.\npub mod {module} {{",
        source.protocol.name
    );
    let _ = writeln!(
        out,
        "    /// Interface pointers for every message argument that names an object.\n\
         \x20   ///\n\
         \x20   /// One table for the whole protocol; each message stores an offset into it,\n\
         \x20   /// which is the layout `wayland-scanner` produces and the layout the\n\
         \x20   /// generator's tests pin.\n\
         \x20   static TYPES: [{ffi}::WlInterfacePtr; {}] = [",
        table.len()
    );
    for entry in &table {
        match entry {
            None => {
                let _ = writeln!(out, "        {ffi}::WlInterfacePtr::NULL,");
            }
            Some(path) => {
                let _ = writeln!(
                    out,
                    "        {ffi}::WlInterfacePtr::new(&super::{path}::INTERFACE),"
                );
            }
        }
    }
    out.push_str("    ];\n");

    let mut next = 0;
    for interface in &source.protocol.interfaces {
        let count = interface.requests.len() + interface.events.len();
        emit_interface(out, interface, &offsets[next..next + count], index, ffi);
        next += count;
    }

    out.push_str("}\n");
    Ok(())
}

fn emit_interface(
    out: &mut String,
    interface: &Interface,
    offsets: &[usize],
    index: &InterfaceIndex,
    ffi: &str,
) {
    let name = &interface.name;
    let _ = writeln!(
        out,
        "\n    /// The `{name}` interface.\n    pub mod {name} {{"
    );
    let _ = writeln!(
        out,
        "        /// Wire name, as it appears in `wl_registry.global`.\n\
         \x20       pub const NAME: &core::ffi::CStr = c\"{name}\";\n\
         \x20       /// Highest version the vendored XML describes.\n\
         \x20       pub const VERSION: u32 = {};",
        interface.version
    );

    for (opcode, message) in interface.requests.iter().enumerate() {
        let _ = writeln!(
            out,
            "        /// Opcode of the `{}` request.\n\
             \x20       pub const REQ_{}: u32 = {opcode};",
            message.name,
            message.name.to_uppercase()
        );
    }
    for (opcode, message) in interface.events.iter().enumerate() {
        let _ = writeln!(
            out,
            "        /// Opcode of the `{}` event.\n\
             \x20       pub const EVT_{}: u32 = {opcode};",
            message.name,
            message.name.to_uppercase()
        );
    }

    let (request_offsets, event_offsets) = offsets.split_at(interface.requests.len());
    emit_message_table(out, "REQUESTS", &interface.requests, request_offsets, ffi);
    emit_message_table(out, "EVENTS", &interface.events, event_offsets, ffi);
    let _ = writeln!(
        out,
        "        /// The `wl_interface` descriptor libwayland and the graphics driver both read.\n\
         \x20       pub static INTERFACE: {ffi}::WlInterface =\n\
         \x20           {ffi}::WlInterface::new(NAME, {}, &REQUESTS, &EVENTS);",
        interface.version
    );

    emit_requests(out, interface, index, ffi);
    emit_events(out, interface, ffi);
    emit_enums(out, interface);

    out.push_str("    }\n");
}

fn emit_message_table(
    out: &mut String,
    kind: &str,
    messages: &[Message],
    offsets: &[usize],
    ffi: &str,
) {
    let _ = writeln!(
        out,
        "        static {kind}: [{ffi}::WlMessage; {}] = [",
        messages.len()
    );
    for (message, offset) in messages.iter().zip(offsets) {
        let _ = writeln!(
            out,
            "            {ffi}::WlMessage::new(c\"{}\", c\"{}\", core::ptr::from_ref(&super::TYPES[{offset}]).cast()),",
            message.name,
            message.signature(),
        );
    }
    out.push_str("        ];\n");
}

fn request_param_type(arg: &Arg, ffi: &str) -> Option<String> {
    Some(match arg.ty {
        ArgType::Int | ArgType::Fixed | ArgType::Fd => "i32".to_string(),
        ArgType::Uint => "u32".to_string(),
        ArgType::String if arg.allow_null => "Option<&core::ffi::CStr>".to_string(),
        ArgType::String => "&core::ffi::CStr".to_string(),
        ArgType::Object => format!("*mut {ffi}::WlProxy"),
        ArgType::Array => format!("*const {ffi}::WlArray"),
        ArgType::NewId => return None,
    })
}

fn argument_initializer(arg: &Arg, ffi: &str) -> String {
    let name = escape_ident(&arg.name);
    match arg.ty {
        ArgType::Int | ArgType::Fixed => format!("{ffi}::WlArgument {{ i: {name} }}"),
        ArgType::Uint => format!("{ffi}::WlArgument {{ u: {name} }}"),
        ArgType::Fd => format!("{ffi}::WlArgument {{ h: {name} }}"),
        ArgType::Array => format!("{ffi}::WlArgument {{ a: {name} }}"),
        ArgType::Object => format!("{ffi}::WlArgument {{ o: {name} }}"),
        ArgType::String if arg.allow_null => format!(
            "{ffi}::WlArgument {{ s: match {name} {{ Some(value) => value.as_ptr(), None => core::ptr::null() }} }}"
        ),
        ArgType::String => format!("{ffi}::WlArgument {{ s: {name}.as_ptr() }}"),
        // A typed `new_id` is a placeholder libwayland overwrites with the
        // proxy it creates. An untyped one — the `wl_registry.bind` shape —
        // expands to interface name, version and that same placeholder.
        ArgType::NewId if arg.interface.is_some() => {
            format!("{ffi}::WlArgument {{ o: core::ptr::null_mut() }}")
        }
        ArgType::NewId => format!(
            "{ffi}::WlArgument {{ s: interface.name }}, {ffi}::WlArgument {{ u: version }}, {ffi}::WlArgument {{ o: core::ptr::null_mut() }}"
        ),
    }
}

fn emit_requests(out: &mut String, interface: &Interface, index: &InterfaceIndex, ffi: &str) {
    for (opcode, message) in interface.requests.iter().enumerate() {
        let constructed = message
            .args
            .iter()
            .find(|arg| arg.ty == ArgType::NewId)
            .map(|arg| arg.interface.clone());

        let mut params = vec![format!("proxy: *mut {ffi}::WlProxy")];
        for arg in &message.args {
            match request_param_type(arg, ffi) {
                Some(ty) => params.push(format!("{}: {ty}", escape_ident(&arg.name))),
                // An untyped `new_id`: the caller supplies the interface and
                // the version to bind at.
                None if arg.interface.is_none() => {
                    params.push(format!("interface: &'static {ffi}::WlInterface"));
                    params.push("version: u32".to_string());
                }
                None => {}
            }
        }

        let slots: usize = message.type_slots().len();
        let (interface_expr, version_expr, returns) = match &constructed {
            Some(Some(target)) => (
                format!(
                    "&raw const super::super::{}::INTERFACE",
                    index.path(target).unwrap_or(target)
                ),
                format!("{ffi}::proxy_version(proxy)"),
                format!(" -> *mut {ffi}::WlProxy"),
            ),
            Some(None) => (
                "core::ptr::from_ref(interface)".to_string(),
                "version".to_string(),
                format!(" -> *mut {ffi}::WlProxy"),
            ),
            None => (
                "core::ptr::null()".to_string(),
                format!("{ffi}::proxy_version(proxy)"),
                String::new(),
            ),
        };

        let _ = writeln!(
            out,
            "\n        /// Sends the `{}.{}` request.\n\
             \x20       ///\n\
             \x20       /// # Safety\n\
             \x20       ///\n\
             \x20       /// `proxy` must be a live `{}` on a connection that is still open, every\n\
             \x20       /// object argument must be live on that same connection, and the caller\n\
             \x20       /// must be on the thread that owns it.\n\
             \x20       pub unsafe fn {}({}){returns} {{",
            interface.name,
            message.name,
            interface.name,
            escape_ident(&message.name),
            params.join(", ")
        );
        let _ = writeln!(
            out,
            "            let mut args: [{ffi}::WlArgument; {slots}] = [{}];",
            message
                .args
                .iter()
                .map(|arg| argument_initializer(arg, ffi))
                .collect::<Vec<_>>()
                .join(", ")
        );
        let flags = if message.destructor {
            format!("{ffi}::MARSHAL_FLAG_DESTROY")
        } else {
            "0".to_string()
        };
        let trailer = if constructed.is_some() { "" } else { ";" };
        let _ = writeln!(
            out,
            "            // SAFETY: the caller guarantees `proxy` and every object argument are\n\
             \x20           // live on an open connection. `args` matches this opcode's signature\n\
             \x20           // by construction and outlives the call, which is libwayland's\n\
             \x20           // requirement for the argument array.\n\
             \x20           unsafe {{\n\
             \x20               {ffi}::marshal(\n\
             \x20                   proxy,\n\
             \x20                   {opcode},\n\
             \x20                   {interface_expr},\n\
             \x20                   {version_expr},\n\
             \x20                   {flags},\n\
             \x20                   args.as_mut_ptr(),\n\
             \x20               )\n\
             \x20           }}{trailer}\n\
             \x20       }}"
        );
    }
}

/// Whether any event borrows from libwayland's closure storage, which decides
/// whether the generated `Event` enum carries a lifetime at all.
fn event_borrows(interface: &Interface) -> bool {
    interface
        .events
        .iter()
        .flat_map(|message| &message.args)
        .any(|arg| matches!(arg.ty, ArgType::String | ArgType::Array))
}

fn event_field_type(arg: &Arg, ffi: &str, borrows: bool) -> String {
    let lifetime = if borrows { "'a " } else { "" };
    match arg.ty {
        ArgType::Int | ArgType::Fixed | ArgType::Fd => "i32".to_string(),
        ArgType::Uint => "u32".to_string(),
        ArgType::String if arg.allow_null => format!("Option<&{lifetime}core::ffi::CStr>"),
        ArgType::String => format!("&{lifetime}core::ffi::CStr"),
        ArgType::Array => format!("&{lifetime}[u8]"),
        ArgType::Object | ArgType::NewId => format!("*mut {ffi}::WlProxy"),
    }
}

fn event_field_expression(arg: &Arg, slot: usize, ffi: &str) -> String {
    let read = format!("(*args.add({slot}))");
    match arg.ty {
        ArgType::Int | ArgType::Fixed => format!("unsafe {{ {read}.i }}"),
        ArgType::Uint => format!("unsafe {{ {read}.u }}"),
        ArgType::Fd => format!("unsafe {{ {read}.h }}"),
        ArgType::String if arg.allow_null => format!("unsafe {{ {ffi}::cstr_arg_opt({read}.s) }}"),
        ArgType::String => format!("unsafe {{ {ffi}::cstr_arg({read}.s) }}"),
        ArgType::Array => format!("unsafe {{ {ffi}::array_arg({read}.a) }}"),
        ArgType::Object | ArgType::NewId => format!("unsafe {{ {read}.o }}"),
    }
}

fn emit_events(out: &mut String, interface: &Interface, ffi: &str) {
    let borrows = event_borrows(interface);
    let decl = if borrows { "<'a>" } else { "" };

    let _ = writeln!(
        out,
        "\n        /// An event the compositor sent on a `{}`.\n\
         \x20       #[derive(Clone, Copy, Debug)]\n\
         \x20       pub enum Event{decl} {{",
        interface.name
    );
    for message in &interface.events {
        let _ = writeln!(out, "            /// The `{}` event.", message.name);
        if message.args.is_empty() {
            let _ = writeln!(out, "            {},", camel_case(&message.name));
            continue;
        }
        let _ = writeln!(out, "            {} {{", camel_case(&message.name));
        for arg in &message.args {
            let _ = writeln!(
                out,
                "                /// The `{}` argument.\n\
                 \x20               {}: {},",
                arg.name,
                escape_ident(&arg.name),
                event_field_type(arg, ffi, borrows)
            );
        }
        out.push_str("            },\n");
    }
    out.push_str("        }\n");

    let (generics, ret) = if borrows {
        ("<'a>", "Option<Event<'a>>")
    } else {
        ("", "Option<Event>")
    };
    let _ = writeln!(
        out,
        "\n        /// Decodes one event from libwayland's argument array.\n\
         \x20       ///\n\
         \x20       /// `None` for an opcode this build does not know, which is what a compositor\n\
         \x20       /// implementing a newer version of the interface sends.\n\
         \x20       ///\n\
         \x20       /// # Safety\n\
         \x20       ///\n\
         \x20       /// `args` must be the argument array libwayland passed for `opcode` on a\n\
         \x20       /// `{}` proxy. Borrowed strings and arrays point into libwayland's closure\n\
         \x20       /// storage and are valid only until the dispatcher returns.\n\
         \x20       #[must_use]\n\
         \x20       pub unsafe fn decode_event{generics}(opcode: u32, args: *const {ffi}::WlArgument) -> {ret} {{",
        interface.name
    );
    if interface.events.is_empty() {
        out.push_str("            let _ = (opcode, args);\n            None\n        }\n");
        return;
    }
    out.push_str("            let _ = args;\n            match opcode {\n");
    for (opcode, message) in interface.events.iter().enumerate() {
        if message.args.is_empty() {
            let _ = writeln!(
                out,
                "                {opcode} => Some(Event::{}),",
                camel_case(&message.name)
            );
            continue;
        }
        let _ = writeln!(
            out,
            "                {opcode} => Some(Event::{} {{",
            camel_case(&message.name)
        );
        for (slot, arg) in message.args.iter().enumerate() {
            let _ = writeln!(
                out,
                "                    {}: {},",
                escape_ident(&arg.name),
                event_field_expression(arg, slot, ffi)
            );
        }
        out.push_str("                }),\n");
    }
    out.push_str("                _ => None,\n            }\n        }\n");
}

fn emit_enums(out: &mut String, interface: &Interface) {
    for enumeration in &interface.enums {
        let kind = if enumeration.bitfield {
            "flags"
        } else {
            "values"
        };
        let _ = writeln!(
            out,
            "\n        /// The `{}.{}` {kind}.\n        pub mod {} {{",
            interface.name,
            enumeration.name,
            escape_ident(&enumeration.name)
        );
        for (name, value) in &enumeration.entries {
            let _ = writeln!(
                out,
                "            /// The `{name}` entry.\n            pub const {}: u32 = {value};",
                const_name(name)
            );
        }
        out.push_str("        }\n");
    }
}

/// Rust keywords that could appear as a Wayland message, argument or enum name.
///
/// `xdg_toplevel.move` is the one that actually bites; the rest are here so a
/// future protocol addition fails to build rather than generating `fn type(`.
const KEYWORDS: &[&str] = &[
    "as", "async", "await", "become", "box", "break", "const", "continue", "crate", "do", "dyn",
    "else", "enum", "extern", "false", "final", "fn", "for", "gen", "if", "impl", "in", "let",
    "loop", "macro", "match", "mod", "move", "mut", "override", "priv", "pub", "ref", "return",
    "static", "struct", "trait", "true", "try", "type", "typeof", "unsafe", "unsized", "use",
    "virtual", "where", "while", "yield",
];

/// A Wayland name as a Rust identifier, raw-escaped where it is a keyword.
fn escape_ident(name: &str) -> String {
    if KEYWORDS.contains(&name) {
        format!("r#{name}")
    } else {
        name.to_string()
    }
}

/// A Wayland enum entry name as a Rust constant.
///
/// `wl_output.transform` has entries literally named `90` and `180`, which are
/// not identifiers; they become `_90` and `_180`.
fn const_name(name: &str) -> String {
    let upper = name.to_uppercase();
    if upper.starts_with(|c: char| c.is_ascii_digit()) {
        format!("_{upper}")
    } else {
        upper
    }
}

/// `set_buffer_scale` → `SetBufferScale`.
fn camel_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for word in name.split('_') {
        let mut chars = word.chars();
        if let Some(first) = chars.next() {
            out.extend(first.to_uppercase());
            out.push_str(chars.as_str());
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parse_protocol;

    #[test]
    fn identifier_escaping_covers_the_real_collisions() {
        assert_eq!(camel_case("set_buffer_scale"), "SetBufferScale");
        assert_eq!(camel_case("close"), "Close");
        assert_eq!(escape_ident("move"), "r#move", "xdg_toplevel.move");
        assert_eq!(escape_ident("attach"), "attach");
        assert_eq!(const_name("90"), "_90", "wl_output.transform.90");
        assert_eq!(const_name("activated"), "ACTIVATED");
    }

    #[test]
    fn an_unresolvable_interface_reference_is_an_error_not_a_null() {
        let protocol = parse_protocol(
            r#"<protocol name="p"><interface name="a" version="1">
                 <request name="get"><arg name="thing" type="new_id" interface="b"/></request>
               </interface></protocol>"#,
        )
        .expect("well-formed");
        let error = emit(
            &[Source {
                module: "p",
                protocol,
            }],
            &Options::default(),
        )
        .expect_err("interface b is undefined");
        assert_eq!(error.interface, "b");
        assert!(error.referenced_by.contains("a::get"), "{error}");
    }

    #[test]
    fn a_protocol_with_no_arguments_anywhere_still_emits_a_usable_table() {
        // The degenerate case: an empty table would make `&TYPES[0]` fail to
        // compile, so one null entry stands in. Every offset is 0 and no
        // message reads a slot, so it is byte-equivalent.
        let protocol = parse_protocol(
            r#"<protocol name="p"><interface name="a" version="1">
                 <request name="destroy" type="destructor"/>
               </interface></protocol>"#,
        )
        .expect("well-formed");
        let generated = emit(
            &[Source {
                module: "p",
                protocol,
            }],
            &Options::default(),
        )
        .expect("emits");
        assert!(generated.contains("WlInterfacePtr; 1]"), "{generated}");
        assert!(generated.contains("&super::TYPES[0]"));
    }
}
