#!/usr/bin/env bash
# Compile `shaders/*.slang` to the committed SPIR-V in `spirv/`, the WGSL in
# `wgsl/` and the MSL in `msl/`, and rewrite `spirv/manifest.txt`.
#
#   crates/crcbl-shaders/tools/compile-shaders.sh            # regenerate
#   crates/crcbl-shaders/tools/compile-shaders.sh --check     # verify only
#
# # Why the artifacts are committed
#
# `docs/plan/02-vulkan-backend.md` §2.3 chooses Slang, and its own risk list
# names the escape hatch this script implements: "Slang toolchain friction in
# build.rs. Fallback: check in compiled SPIR-V alongside sources until the
# toolchain story is smooth."
#
# The consequence is that **`cargo build` needs no shader compiler at all** —
# not on a contributor's machine, not on the macOS and Windows CI legs, not in
# the `test (linux)` job. `build.rs` only ever *verifies*, and it verifies with
# SHA-256 rather than by recompiling, so the check is identical everywhere.
#
# # --check is the anti-rot gate
#
# `--check` recompiles every source with the pinned `slangc` and demands the
# result be byte-for-byte what is committed. It runs in CI (which installs the
# pinned compiler; see `.github/workflows/ci.yml`), so "someone edited the
# `.slang` and forgot to regenerate" is caught by a machine that is not the
# author's. The version pin is load-bearing: two Slang releases legitimately
# emit different SPIR-V for identical source, so an unpinned byte comparison
# would fail for a reason that is not drift.
#
# ENVIRONMENT
#   CRCBL_SLANGC   Path to `slangc`. Default: whatever is on PATH.

set -euo pipefail

CRATE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Pinned in exactly one place, and read by CI. Bumping it is a deliberate act
# that re-blesses every artifact in the same commit — which is also the moment
# to re-bless any golden image the new codegen moved.
SLANG_VERSION="2026.14"
# Vulkan 1.3 accepts SPIR-V 1.6; 1.5 is the floor every 1.3 driver has had
# since launch and nothing here needs a 1.6 instruction.
SLANG_PROFILE="spirv_1_5"

CHECK_ONLY=0
if [ "${1:-}" = "--check" ]; then
    CHECK_ONLY=1
    shift
fi
if [ "$#" -gt 0 ]; then
    echo "crcbl shaders: unexpected argument '$1'; usage: compile-shaders.sh [--check]" >&2
    exit 2
fi

SLANGC="${CRCBL_SLANGC:-slangc}"
if ! command -v "$SLANGC" >/dev/null 2>&1; then
    cat >&2 <<EOF
crcbl shaders: no \`slangc\` found (looked for '$SLANGC').

This script is the only thing that needs one — \`cargo build\` does not, because
the compiled SPIR-V is committed. Install it only if you are editing a shader:

  curl -sL -o slang.tar.gz \\
    https://github.com/shader-slang/slang/releases/download/v${SLANG_VERSION}/slang-${SLANG_VERSION}-linux-x86_64-glibc-2.27.tar.gz
  mkdir -p ~/.local/slang && tar xzf slang.tar.gz -C ~/.local/slang
  export CRCBL_SLANGC=~/.local/slang/bin/slangc

Use exactly v${SLANG_VERSION}: the artifacts are compared byte-for-byte.
EOF
    exit 1
fi

FOUND_VERSION="$("$SLANGC" -v 2>&1 | tr -d '\r' | tail -1)"
if [ "$FOUND_VERSION" != "$SLANG_VERSION" ]; then
    echo "crcbl shaders: \`$SLANGC\` is version '$FOUND_VERSION', but the artifacts are" >&2
    echo "  pinned to '$SLANG_VERSION'. Different releases emit different SPIR-V for the" >&2
    echo "  same source, so this would produce spurious drift. Install the pinned one, or" >&2
    echo "  bump SLANG_VERSION here and re-bless every artifact and golden image together." >&2
    exit 1
fi

cd "$CRATE_DIR"
mkdir -p spirv
mkdir -p wgsl
mkdir -p msl

WORK="$(mktemp -d -t crcbl-shaders.XXXXXX)"
trap 'rm -rf "$WORK"' EXIT INT TERM

MANIFEST="$WORK/manifest.txt"
{
    echo "# Generated by tools/compile-shaders.sh — do not edit by hand."
    echo "#"
    echo "# \`build.rs\` fails the build when a source's SHA-256 stops matching the one"
    echo "# recorded here, which is how a shader edited without regenerating its artifact"
    echo "# is caught on a machine with no shader compiler at all."
    echo "slangc-version = $SLANG_VERSION"
    echo "target = $SLANG_PROFILE"
} >"$MANIFEST"

STATUS=0
SHADERS=(shaders/*.slang)
if [ ! -e "${SHADERS[0]}" ]; then
    echo "crcbl shaders: no shaders/*.slang to compile" >&2
    exit 1
fi

for SOURCE in "${SHADERS[@]}"; do
    NAME="$(basename "$SOURCE" .slang)"
    ARTIFACT="spirv/${NAME}.spv"
    FRESH="$WORK/${NAME}.spv"
    WGSL_ARTIFACT="wgsl/${NAME}.wgsl"
    FRESH_WGSL="$WORK/${NAME}.wgsl"
    MSL_ARTIFACT="msl/${NAME}.metal"
    FRESH_MSL="$WORK/${NAME}.metal"

    echo "crcbl shaders: compiling $SOURCE → SPIR-V"
    "$SLANGC" "$SOURCE" \
        -target spirv \
        -profile "$SLANG_PROFILE" \
        -emit-spirv-directly \
        -o "$FRESH"

    echo "crcbl shaders: compiling $SOURCE → WGSL"
    "$SLANGC" "$SOURCE" \
        -target wgsl \
        -profile "$SLANG_PROFILE" \
        -o "$FRESH_WGSL"

    # The Metal backend compiles this at run time through
    # `MTLDevice::newLibraryWithSource:options:error:`, so the artifact is MSL
    # *source* rather than a `.metallib` — there is no offline Metal compiler
    # off macOS, and committing one would put a macOS-only step in the middle of
    # a script every leg of CI runs.
    echo "crcbl shaders: compiling $SOURCE → MSL"
    "$SLANGC" "$SOURCE" \
        -target metal \
        -profile "$SLANG_PROFILE" \
        -o "$FRESH_MSL"

    # A compiler that emitted something the driver will reject is worse than one
    # that failed, because the failure moves to `vkCreateShaderModule` on
    # someone else's machine.
    if command -v spirv-val >/dev/null 2>&1; then
        spirv-val --target-env vulkan1.3 "$FRESH"
    else
        echo "crcbl shaders: no spirv-val; skipping validation of $ARTIFACT" >&2
    fi

    # `OpEntryPoint`'s execution model and name, straight out of the artifact
    # rather than restated by hand — the manifest must describe what was built.
    if command -v spirv-dis >/dev/null 2>&1; then
        # The entry-point *name* is matched against `OpEntryPoint` at pipeline
        # creation, so its case is load-bearing and must survive verbatim; only
        # the execution model is normalised to the seam's lower-case spelling.
        ENTRY_POINTS="$(spirv-dis "$FRESH" \
            | sed -n 's/.*OpEntryPoint \([A-Za-z]*\) %[^ ]* "\([^"]*\)".*/\2:\L\1/p' \
            | paste -sd, - \
            | sed 's/,/, /g')"
    else
        echo "crcbl shaders: no spirv-dis; cannot record entry points" >&2
        exit 1
    fi
    if [ -z "$ENTRY_POINTS" ]; then
        echo "crcbl shaders: $SOURCE declares no entry points" >&2
        exit 1
    fi

    if [ "$CHECK_ONLY" -eq 1 ]; then
        if ! cmp -s "$FRESH" "$ARTIFACT"; then
            echo "crcbl shaders: $ARTIFACT does not match a fresh compile of $SOURCE." >&2
            echo "  Run crates/crcbl-shaders/tools/compile-shaders.sh and commit the result." >&2
            echo "  A rendering change that shifts output must also re-bless its golden" >&2
            echo "  image (docs/plan/12-testing.md)." >&2
            STATUS=1
        fi
        if ! cmp -s "$FRESH_WGSL" "$WGSL_ARTIFACT"; then
            echo "crcbl shaders: $WGSL_ARTIFACT does not match a fresh compile of $SOURCE." >&2
            echo "  Run crates/crcbl-shaders/tools/compile-shaders.sh and commit the result." >&2
            STATUS=1
        fi
        if ! cmp -s "$FRESH_MSL" "$MSL_ARTIFACT"; then
            echo "crcbl shaders: $MSL_ARTIFACT does not match a fresh compile of $SOURCE." >&2
            echo "  Run crates/crcbl-shaders/tools/compile-shaders.sh and commit the result." >&2
            STATUS=1
        fi
    else
        cp "$FRESH" "$ARTIFACT"
        cp "$FRESH_WGSL" "$WGSL_ARTIFACT"
        cp "$FRESH_MSL" "$MSL_ARTIFACT"
    fi

    {
        echo
        echo "[$NAME]"
        echo "source = $SOURCE"
        echo "source-sha256 = $(sha256sum "$SOURCE" | cut -d' ' -f1)"
        echo "spirv = $ARTIFACT"
        echo "spirv-sha256 = $(sha256sum "$FRESH" | cut -d' ' -f1)"
        echo "wgsl = $WGSL_ARTIFACT"
        echo "wgsl-sha256 = $(sha256sum "$FRESH_WGSL" | cut -d' ' -f1)"
        echo "msl = $MSL_ARTIFACT"
        echo "msl-sha256 = $(sha256sum "$FRESH_MSL" | cut -d' ' -f1)"
        echo "entry-points = $ENTRY_POINTS"
    } >>"$MANIFEST"
done

if [ "$CHECK_ONLY" -eq 1 ]; then
    if ! diff -u spirv/manifest.txt "$MANIFEST" >/dev/null 2>&1; then
        echo "crcbl shaders: spirv/manifest.txt is stale:" >&2
        diff -u spirv/manifest.txt "$MANIFEST" >&2 || true
        STATUS=1
    fi
    if [ "$STATUS" -eq 0 ]; then
        echo "crcbl shaders: every artifact matches its source (slangc $SLANG_VERSION)"
    fi
    exit "$STATUS"
fi

cp "$MANIFEST" spirv/manifest.txt
echo "crcbl shaders: regenerated ${#SHADERS[@]} artifact(s) and spirv/manifest.txt"
