//! Bakes `assets/*.crpix` into the PNG + Aseprite-sidecar pair the engine
//! reads, and generates the table `src/art.rs` includes.
//!
//! ```text
//! assets/actors.crpix ──parse──▶ CrpixArt ──bake──▶ $OUT_DIR/actors.png
//!                                               └─▶ $OUT_DIR/actors.json
//!                                     │
//!                                     └──▶ $OUT_DIR/art_data.rs (include_bytes!)
//! ```
//!
//! **This is the fifth copy of this script**, after `apps/flappy/build.rs`,
//! `apps/breakout/build.rs`, `crates/crcbl-render/build.rs` and
//! `apps/asteroids/build.rs`. They differ in their `ASSETS` array and in nothing
//! else. `docs/backlog.md` has carried the fix since the second copy — a
//! `bake::bake_dir(manifest, out, &stems, hz)` entry point in `crcbl-sprite`,
//! because a build script *can* depend on a workspace library and that is the
//! only shape that removes the copy rather than moving it — and
//! `docs/plan/ROADMAP.md` says it was owed "before the third sample". It was not
//! paid before the fourth either: closing it is a change to `crcbl-sprite` and
//! to four other build scripts, and this slice is the art. The backlog entry is
//! updated with the count rather than left saying four.
//!
//! # Why the baked files are not committed
//!
//! `docs/specs/crcbl/pix.md` is explicit that `.crpix` is a **build input** and
//! that nothing downstream knows it exists. Committing the PNG beside the text
//! would create two sources of truth for the same picture, and the one a
//! reviewer reads in a diff would be the one that is not loaded.
//!
//! # This runs on the host, for every target
//!
//! A build script is compiled and run for the *host* whatever the target is, so
//! a `wasm32-unknown-unknown` build of this crate gets the same bytes, already
//! baked, through `include_bytes!`. Nothing reads a file at runtime on any
//! target.

use std::path::{Path, PathBuf};

/// The tick rate the frame holds are baked against.
///
/// A `.crpix` counts holds in **simulation ticks** and an Aseprite sidecar
/// counts milliseconds, so the pair has to be converted on the way out and back
/// on the way in — and the two conversions must use the same rate or every hold
/// changes. `src/art.rs`'s `ART_TICK_HZ` is the other half.
///
/// Nothing horde draws is animated: an enemy is a still frame at a moving
/// position, and nothing in this game even turns. So no hold here is longer than
/// the default of one tick, and the guard in `art.rs` is as weak as breakout's
/// and asteroids' for the same reason — recorded in `docs/backlog.md`.
const ART_TICK_HZ: u32 = 60;

/// The sheets, by file stem. Each is `assets/<stem>.crpix`.
///
/// **Two, and the split is a batching decision rather than an artistic one.**
/// `assets/actors.crpix` carries the player, all three enemy kinds and the XP
/// pickup in one 34-texel frame size, so the whole field is a single
/// `SpriteRenderer` batch whatever order it is emitted in; the shot is 8 texels
/// and gets its own sheet rather than a twenty-times-oversized quad. Both files
/// carry the argument at length.
const ASSETS: [&str; 2] = ["actors", "bolt"];

fn main() {
    let root = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("cargo always sets CARGO_MANIFEST_DIR"),
    );
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("cargo always sets OUT_DIR"));

    let mut table =
        String::from("// @generated by build.rs from apps/horde/assets/*.crpix — do not edit.\n\n");

    for stem in ASSETS {
        let relative = format!("assets/{stem}.crpix");
        // **The line that makes editing art rebuild the game.** Without it the
        // baked PNG in OUT_DIR is a cached artifact of a source cargo has never
        // been told about, and a redrawn enemy shows up on the next
        // `cargo clean` and not before.
        println!("cargo::rerun-if-changed={relative}");

        let source = root.join(&relative);
        let text = std::fs::read_to_string(&source)
            .unwrap_or_else(|error| fail(&format!("{relative}: {error}")));
        let art = crcbl_sprite::crpix::parse(&text)
            .unwrap_or_else(|error| fail(&format!("{relative}:{error}")));

        let image = format!("{stem}.png");
        let baked = crcbl_sprite::bake::bake(&art, &image, ART_TICK_HZ)
            .unwrap_or_else(|error| fail(&format!("{relative}: {error}")));

        let png = out.join(&image);
        write(&png, &baked.png);
        let upper = stem.to_uppercase();
        table.push_str(&format!(
            "pub static {upper}_PNG: &[u8] = include_bytes!({:?});\n",
            png.display().to_string()
        ));

        match &baked.json {
            Some(json) => {
                let sidecar = out.join(format!("{stem}.json"));
                write(&sidecar, json.as_bytes());
                table.push_str(&format!(
                    "pub static {upper}_JSON: Option<&str> = Some(include_str!({:?}));\n",
                    sidecar.display().to_string()
                ));
            }
            // A single still frame is fully described by its image; the loader
            // takes `None` and reads one frame covering the whole picture.
            None => table.push_str(&format!("pub static {upper}_JSON: Option<&str> = None;\n")),
        }
    }

    write(&out.join("art_data.rs"), table.as_bytes());
}

fn write(path: &Path, bytes: &[u8]) {
    std::fs::write(path, bytes)
        .unwrap_or_else(|error| fail(&format!("writing {}: {error}", path.display())));
}

/// Fails the build with a message cargo shows, rather than a panic backtrace.
fn fail(message: &str) -> ! {
    println!("cargo::error={message}");
    std::process::exit(1);
}
