//! viewer in a browser: the exports a page drives this sample through.
//!
//! # What is different here, and why this file is not the other samples' file
//!
//! Every other sample's browser half is `crcbl::impl_web_pending!` and nothing
//! else, because every other sample's start-up needs only a window and its own
//! `Options::default()`. This one opens with a **document**. The viewer's whole
//! subject is a glTF file, its renderer is built out of one, and a page has no
//! path to name and no filesystem to name it in — so the document is generated
//! into the module by [`crate::demo_model`] and read out of memory.
//!
//! That is the difference the seam had to grow for:
//! [`crcbl::engine::PolledGpu::Context`] is what carries the document through
//! the device request, and it exists because the alternative was opening with
//! nothing resident and swapping the real scene in afterwards — a renderer
//! built twice at every start-up to work around a signature.
//!
//! # What a visitor sees, and what they do not
//!
//! The **native** viewer is pointed at a file. This one shows the document it
//! ships with; there is no drop target yet, which is
//! `docs/plan/sample/05-viewer.md`'s V-F5 and is written up in
//! `docs/backlog.md`. Everything past the loading is the same code the native
//! viewer runs: the orbit camera, the frame-on-load, the grid scaled to the
//! document, the listing behind `I`, the wireframe and normals views, and the
//! exposure slider.
//!
//! The re-export watch is native-only in effect. [`crate::watch`] polls a path,
//! and a page has none, so it never fires — the loop carries it and nothing
//! happens, which is the honest browser answer rather than a second code path.
//!
//! # The boot sequence
//!
//! ```text
//! __crcbl_viewer_prepare()   // log sink and storage backends exist
//! __crcbl_viewer_boot()      // window opened, device requested
//! __crcbl_web_resize(w, h)   // the canvas has a size — this starts the device
//! __crcbl_viewer_frame(now)  // once per rAF, forever
//! ```
//!
//! **The first `__crcbl_web_resize` is what starts the device request.** A
//! canvas has no size until the document gives it one, and a swapchain needs
//! one; a shim that never calls `resize` leaves the status at `BOOTING`
//! forever.

use std::rc::Rc;

use crate::app::{Loop, PendingLoop};
use crate::args::Options;

// The status codes and the asset base are the shim's wire format, so they have
// exactly one definition; see [`crcbl::web`]. Re-exported rather than reached
// through the path, because this module's own docs name them.
pub use crcbl::web::{
    ASSET_BASE, STATUS_BOOTING, STATUS_FAILED, STATUS_IDLE, STATUS_PAUSED, STATUS_PREPARED,
    STATUS_RUNNING, STATUS_STOPPED,
};

// ---------------------------------------------------------------------------
// This sample's half of the lifecycle
// ---------------------------------------------------------------------------

// **There is no `WebLoop` impl here.** `crcbl::web` blanket-implements it for
// every `crcbl::engine::Loop`, and the two halves that were ever this sample's
// — its name and the log line a finished run is worth — are `HostedGame::NAME`
// and `HostedGame::log_summary` in `app.rs`.
//
// **`crcbl::impl_web_pending!` is deliberately not used.** That macro's whole
// body is `Self::request(shell, &Options::default(), clock)`, and this sample's
// `PendingLoop::request` takes a fourth argument the macro has no way to supply:
// the document. Written out, the forwards are `PendingLoop::method(..)` rather
// than `Self::method(..)` for the reason that macro documents at length — a
// `Self::` path here would resolve to the trait method and recurse for ever.
// The difference is that a hand-written impl gets rustc's
// `unconditional_recursion` lint, which this workspace denies, and an expansion
// does not: the trap the macro needs a `const _` guard for is one the compiler
// catches here by itself.
impl crcbl::web::WebPending for PendingLoop<dyn crcbl::shell::Shell> {
    type Loop = Loop<dyn crcbl::shell::Shell>;

    fn request(
        shell: Box<dyn crcbl::shell::Shell>,
        clock: crcbl::engine::Clock,
    ) -> Result<Self, crcbl::engine::LoopError> {
        // **The document cannot fail here, and the type says so the hard way.**
        // This trait's error is the *loop's*, `LoopError<Infallible>`, and a
        // document that will not parse is not one of its variants — rightly,
        // because `LoopError` describes a window system, a device and a game
        // refusing, and none of those is what a bad `.glb` is.
        //
        // Nothing is being swallowed. These bytes are generated by
        // `crate::demo_model` and compiled into this module: no visitor chose
        // them, no filesystem served them, and they cannot differ between one
        // page load and the next. `demo_model`'s
        // `the_demo_document_loads_through_the_real_loader` runs this exact
        // call natively on every build and asserts what comes out, so a change
        // that broke it fails there rather than in a browser.
        //
        // The native viewer keeps the honest `ViewerError::Load` for its own
        // path, where a person really does hand it a file that might be wrong.
        let model = crate::demo_model::demo_document()
            .expect("the document compiled into this module loads; demo_model's tests hold it");
        PendingLoop::request(shell, &browser_options(), clock, Rc::new(model))
            .map_err(into_loop_error)
    }

    fn poll(&mut self) -> Result<Option<Self::Loop>, crcbl::engine::LoopError> {
        PendingLoop::poll(self).map_err(into_loop_error)
    }
}

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

crcbl::web_exports! {
    pending: PendingLoop<dyn crcbl::shell::Shell>,
    prepare: __crcbl_viewer_prepare,
    log_level: __crcbl_viewer_log_level,
    boot: __crcbl_viewer_boot,
    frame: __crcbl_viewer_frame,
    status: __crcbl_viewer_status,
    shutdown: __crcbl_viewer_shutdown,
    error_ptr: __crcbl_viewer_error_ptr,
    error_len: __crcbl_viewer_error_len,
    log_take: __crcbl_viewer_log_take,
    log_ptr: __crcbl_viewer_log_ptr,
}

/// The engine's half of a [`ViewerError`](crate::app::ViewerError), for the
/// trait above.
///
/// `PendingLoop` reports the wider error because it is shared with the native
/// path, where the document is a file that may be missing or malformed.
/// Everything this module can actually provoke is the narrower one — the window
/// and the device — and the `Load` arm is unreachable here for the reason
/// `request` sets out: it never gets that far, because the document is loaded
/// and unwrapped before `PendingLoop` is asked for.
fn into_loop_error(error: crate::app::ViewerError) -> crcbl::engine::LoopError {
    match error {
        crate::app::ViewerError::Engine(error) => error,
        crate::app::ViewerError::Load(error) => unreachable!(
            "the browser path loads its document before start-up begins, so \
             PendingLoop cannot report one: {error}"
        ),
    }
}

/// The options a page opens with.
///
/// Spelled out rather than taken from a `Default` on
/// [`Options`](crate::args::Options), because that type has no sensible one:
/// its `model` is the file the native viewer was told to open, and a `Default`
/// would have to invent a path that names nothing — the kind of placeholder
/// that reads as a real value everywhere it is later used. There is no argv in
/// a browser and nothing here to parse, so this is the whole of it.
///
/// The tick rate is this sample's own
/// [`DEFAULT_TICK_HZ`](crate::args::DEFAULT_TICK_HZ), for the reason
/// [`crcbl::args::Common::new`] takes one at all: a game that integrates at its
/// own rate says so where the value is built, not by overwriting the field
/// afterwards and hoping nothing read it first.
///
/// `model` is the generated document's key rather than a path. Nothing opens
/// it: [`crate::watch`] is the only reader and it polls a filesystem this
/// target has not got, so the watch is built, never fires, and the re-export
/// loop is simply a thing the browser build does not do. The key is what it is
/// given so that a log line naming the watched document says the same thing
/// every other message about this document says.
fn browser_options() -> Options {
    Options {
        common: crcbl::args::Common::new(crate::args::DEFAULT_TICK_HZ),
        model: std::path::PathBuf::from(crate::demo_model::DEMO_KEY),
    }
}
